### ISSUE TITLE
git does not synchronize with branches that are not master

### ISSUE THREAD

**Issue by serweb-labs** [Requarks/wiki#502] opened 2018-04-24 21:14 UTC
### Actual behavior
 - it is not synchronized in a branch other than the master, (need checkout -b custombranch after the first pull?)
 - error log say: Unable to push changes to remote Git repository!
 - "git status" say: On branch master

### Expected behavior
- sync  success 

### Steps to reproduce the behavior
  - use docker-compose deploy
  - enable git and set a "non master" branch in configuration file
  - run container (docker-compose)

thanks :smile:

**Comment by NGPixel** [comment] 2018-04-29 16:14
Duplicate of #227

**Closed by NGPixel** 2018-04-29 16:14 UTC
