### ISSUE TITLE
Migration MSSQL - Error: migration file "2.2.17.js" failed

### ISSUE THREAD

**Issue by LujienZ** [Requarks/wiki#1657] opened 2020-04-01 15:37 UTC
**Describe the bug**
 The start script errors when trying to migrate.

**To Reproduce**
    Install v2.2.51
    Start WikiJS

**Host Info**
    OS: Windows
    Wiki.js version: 2.2.51
    Database engine: Microsoft SQL Server 2012

**Additional context**
Error message : Incorrect syntax near the keyword 'ORDER'
SQL request causing the problem : 
` 
sqlVersionDate = 'UPDATE "pageHistory" h1 SET "versionDate" = COALESCE((SELECT prev."createdAt" FROM "pageHistory" prev WHERE prev."pageId" = h1."pageId" AND prev.id < h1.id ORDER BY prev.id DESC LIMIT 1), h1."createdAt")'
`
File : D:\WikiEudonet\server\db\migrations\2.2.17.js

I fixed the problem with separate case for mssql : 
      sqlVersionDate = 'UPDATE pageHistory SET versionDate = COALESCE((SELECT TOP 1 prev.createdAt FROM pageHistory prev WHERE prev.pageId = pageHistory.pageId AND prev.id < pageHistory.id ORDER BY prev.id DESC), pageHistory.createdAt)'

**Comment by Smankusors** [comment] 2020-04-01 17:19
this is duplicate of https://github.com/Requarks/wiki/issues/1642

**Comment by andjelatomic** [comment] 2020-04-02 11:33
Dears,

I have the other problem. I am  using the MSSQL server, on a different machine, and it was working fine with the previous version, but in the latest one there are some SQL syntax errors, like 

2020-04-02T11:29:38.416Z [MASTER] info: Database Connection Successful [ OK ]
migration file "2.2.17.js" failed
migration failed with error: UPDATE "pageHistory" h1 SET "versionDate" = COALESCE((SELECT prev."createdAt" FROM "pageHistory" prev WHERE prev."pageId" = h1."pageId" AND prev.id < h1.id ORDER BY prev.id DESC LIMIT 1), h1."createdAt") - Incorrect syntax near the keyword 'ORDER'.
2020-04-02T11:29:38.889Z [MASTER] error: Database Initialization Error: UPDATE "pageHistory" h1 SET "versionDate" = COALESCE((SELECT prev."createdAt" FROM "pageHistory" prev WHERE prev."pageId" = h1."pageId" AND prev.id < h1.id ORDER BY prev.id DESC LIMIT 1), h1."createdAt") - Incorrect syntax near the keyword 'ORDER'.
root@wiki01:~/wiki# 

Is there anywhere debugged version, or I have to debug it on my own?

Winds, galaxies and regards
Andjela

**Comment by andjelatomic** [comment] 2020-04-02 11:41
Done! Thank you!

**Comment by NGPixel** [comment] 2020-04-02 15:25
Duplicate of #1642

**Closed by NGPixel** 2020-04-02 15:25 UTC
