### ISSUE TITLE
Redirect to new location after moving/renaming a page

### ISSUE THREAD

**Issue by juliendms** [Requarks/wiki#1243] opened 2019-11-20 15:55 UTC
**Describe the bug**
When moving or renaming a page, after the changes are validated in the pop-up, an error is thrown. 

**To Reproduce**
1. Use an existing page
2. Edit -> Move/Rename
3. Change the location or name of the page
4. Validate the changes
5. See the error (cf. screenshot)

**Expected behavior**
Redirect to the new location of the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/41991731/69254290-55d1fd00-0bb6-11ea-8309-5439eabc8590.png)

**Host Info (please complete the following information):**
 - Wiki.js version: 2.0.1
 - Database engine: PgSQL

**Comment by NGPixel** [comment] 2019-11-20 22:07
Duplicate of #1181

**Closed by NGPixel** 2019-11-20 22:07 UTC
