### ISSUE TITLE
Multiple images cannot be uploaded in a row

### ISSUE THREAD

**Issue by NathanHartkopf** [Requarks/wiki#333] opened 2017-11-23 03:51 UTC
### Actual behavior
Open the image upload dialog while editing a file.
Upload an image `Test-Image-1.jpg` -> Success.

Attempt to upload a second image `Test-Image-2.jpg`
-> "Upload Error: File Test-Image-**_1_**.jpg already exists."

This will continue for an image of any name or size.

### Expected behavior
Open the image upload dialog while editing a file.
Upload an image `Test-Image-1.jpg` -> Success.

Open the image upload dialog while editing a file.
Upload an image `Test-Image-2.jpg` -> Success.

### Steps to reproduce the behavior

See above

**Comment by NGPixel** [comment] 2017-11-23 03:58
Duplicate of #265

**Closed by NGPixel** 2017-11-23 03:58 UTC
