### ISSUE TITLE
GraphQL error: Cannot read property 'code' of null

### ISSUE THREAD

**Issue by ankyfive** [Requarks/wiki#2744] opened 2020-11-23 08:12 UTC
**Describe the bug**
When editing or creating a new page I encounter the follwoing error :
GraphQL error: Cannot read property 'code' of null
I restarted the wiki, but few minutes after the issue happened again.

**To Reproduce**
1. Go to edit'
2. Edit content
3. Click on save

**Expected behavior**
No error should be seen

**Screenshots**

**Host Info (please complete the following information):**
OS: Debian 9.12
Wiki.js version: 2.5.159
Database engine:postgres 9.6.17

**Comment by NGPixel** [comment] 2020-11-23 16:29
Duplicate of #1308

**Closed by NGPixel** 2020-11-23 16:29 UTC
