### ISSUE TITLE
Git Import from 1.x doesn't work

### ISSUE THREAD

**Issue by williambrode** [Requarks/wiki#1664] opened 2020-04-03 04:03 UTC
**Describe the bug**
Docker image 2.2.51 and 2.1.113:
When using import from 1.x - I observed this error: 
Bad port 'undefined' fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. error: Could not fetch origin
Docker image 2.0.12 works fine though - with the same process.

**To Reproduce**
1. Run the docker image
2. Set up admin user
3. Go to utilities -> Import from 1.x -> Uncheck user import.  Fill in git path, private key, ect. and try to run it.

**Expected behavior**
Import should not get the Bad port 'undefined' error.

**Screenshots**

**Host Info (please complete the following information):**
Docker image 2.2.51 and 2.1.113

**Additional context**
Reviewing the commits it looks to me like b1c7edac904e19493ab19b8740c04ae3decf6691 caused this issue because they didn't set a port in \client\components\admin\admin-utilities-importv1.vue where it sets the git config.

**Comment by Smankusors** [comment] 2020-04-03 05:10
This issue is a duplicate of #1654

**Comment by dand561** [comment] 2020-04-09 14:06
I am having the same issue on Ubuntu 19.04 with Postgres. The database on v1 is Mongo, while on v2 it is Postgres. In these conditions, is it possible to import from local folder even though I have git configured in v1? And if the sync is complete and correct, then can I add the git config to the .yml file?

**Comment by oz117** [comment] 2020-04-19 16:59
Hello I just experienced the same issue. Does anyone have an idea of what is happening?
In the meanwhile I switched to basic auth :)

**Comment by NGPixel** [comment] 2020-04-19 19:48
Fixed by 4d8d748b1110cb13ebe551cdf1bb375588eae472

**Closed by NGPixel** 2020-04-19 19:48 UTC
