### ISSUE TITLE
Node.js dont launch

### ISSUE THREAD

**Issue by Aash-Sasha** [Requarks/wiki#15] opened 2017-02-20 15:05 UTC
case1:
when i added a new line "git: false" in the configuration file, node.js command prompt window stopped launching with "wiki start" and localhost:80 became unavailable.
when i removed that line everything became normal

case2:
Node.js command prompt window isnt launching with "wiki start ".
Wiki.js command prompt is showing that wiki.js is launched.
as a result (i think)
MongoD command prompt is not showing any connection,
localhost:80 in browser is showing page not found.

i uninstalled wiki.js and MongoDB and reinstalled them but node.js still not launching.

EDIT:- i reinstalled node.js, now it is launching.

**Comment by NGPixel** [comment] 2017-02-20 18:17
case 1: Duplicate of bug #14 

case 2: The nodejs window isn't supposed to launch when using `wiki start`. Wiki.js is running the background using pm2 process management module. You can verify if Wiki.js is running correctly by running command:

```shell
pm2 status
```

and you can see the live logs using:

```shell
pm2 logs wiki --lines 100
```

Let me know if you have any errors from these logs.

Nick

**Closed** 2017-02-28 02:11 UTC
Labels: investigating
