### ISSUE TITLE
www and without www wikijs setup for https

### ISSUE THREAD

**Issue by sattitan19** [Requarks/wiki#2670] opened 2020-11-06 06:03 UTC
**Question**
i have installed wikijs in digital ocean using the DO wizard and i have setup domain as xyz***.com but when i visit www.xyz***.com..i get certificate error. how do i setup wikijs to visit both the website without certificate error.. there is no option to specify multiple domains in docker command? 

**Host Info (please complete the following information):**
OS: Ubuntu 18.04, Docker
Wiki.js version: 2.5.170
Database engine: postgres 11.8

**Comment by Smankusors** [comment] 2020-11-06 09:33
Duplicate of #2245

**Comment by sattitan19** [comment] 2020-11-06 12:59
i understand this but how do we setup redirect directly on digital ocean then?

**Comment by sattitan19** [comment] 2020-11-06 13:34
i resolved this by using cname entry in digital ocean.

Assuming that you have the default created DNS record set up it will include a main record like this:

`@  IN  A  [DROPLET_IP]`

We can add a CNAME entry by doing the following:

`www  CNAME   @`

This will direct requests for www to the same IP as those for the domain without the www subdomain.

**Closed** 2020-11-06 23:50 UTC
Labels: help
