### ISSUE TITLE
OKTA integration issuw

### ISSUE THREAD

**Issue by madeel-nisum-com** [Requarks/wiki#1957] opened 2020-05-29 10:35 UTC
i was trying to integrate with OKTA and i have follow this KB for integration https://docs.requarks.io/en/auth/okta im getting this error.

![Screen Shot 2020-05-29 at 03 19 53](https://user-images.githubusercontent.com/25505445/83250662-5a76ff80-a15d-11ea-9581-6a2378bd9154.png)

Thank you

**Comment by madeel-nisum-com** [comment] 2020-05-29 17:14
yeah i did and enter the valid site URL and my site is accessible from public network.

**Comment by NGPixel** [comment] 2020-05-29 19:45
Did you add the URL in your okta whitelist config?

**Comment by madeel-nisum-com** [comment] 2020-05-30 01:43
can you let me know .. where i can do that, please.

**Comment by NGPixel** [comment] 2020-05-30 02:46
Have you read the [docs](https://docs.requarks.io/en/auth/okta)?

**Comment by madeel-nisum-com** [comment] 2020-05-31 10:32
yeah i followed the same document for the configuration ....

**Comment by winkelement** [comment] 2020-05-31 19:15
Well i just tested it out of curiosity and got it working without problems...
Maybe double check you have no typo in your redirect URI, org URL? 
Check that everything in your redirect URI is lowercase?
What wiki.js version are you running anyway?

**Comment by madeel-nisum-com** [comment] 2020-06-01 05:14
i cross checked and found URLs are defined correctly ... the wiki.js version is 2.3.81 with Node.js 14.3.0 and PostgreSQL 9.2.24

**Comment by madeel-nisum-com** [comment] 2020-06-01 16:45
Hi @winkelement / @NGPixel 

Thank you for your support and assistance. this issue is fixed now. I think it was happening due to I was tried to make this integration without SSL

thank you

**Comment by Smankusors** [comment] 2020-06-03 14:15
If the issue is fixed, feel free to close this issue now 😃

**Closed** 2020-06-03 14:36 UTC
Labels: help
