### ISSUE TITLE
Cannot upload an image in an exisiting assets folder

### ISSUE THREAD

**Issue by juliendms** [Requarks/wiki#1058] opened 2019-09-24 14:20 UTC
**Describe the bug**
With the new beta, I am unable to add images in an exisiting assets folder. The folder (let say `/test/`) is open, and when I upload a new image it is uploaded in the root directory `/`.

**To Reproduce**
1. Your Assets folder should have at least one existing subfolder, e.g. `/test/`
2. While editing a page, click on Insert Assets and browse to the existing folder (here: `/test/`)
3. Upload an image
4. The image is uploaded in the root folder

**Expected behavior**
The image should be uploaded in `/test/`.

**Host Info:**
 - OS: Centos 7.6.1810
 - Wiki.js version: 2.0.0-beta.303
 - Database engine: postgres 9.2.24

**Additional context**
Interestingly enough, the image is still displayed properly when using the syntax `[img](/test/img.png)`.

Edit: Just to clarify, the folder mechanism works if the folder was created just before. It has to be an existing folder.

**Comment by NGPixel** [comment] 2019-09-28 01:47
I'm not able to reproduce this behavior. Have you tried in another browser?

**Comment by juliendms** [comment] 2019-09-30 13:05
I tried on Chrome and Edge. Same behavior, but it's more tricky than what I wrote in the description. Here is the detailled setp-by-step:

1. Connect to Wiki.JS, edit an existing page and add a new folder (eg `/test`). Verify that you can import an image in this folder.
**2. Clear your browser cache, or open a new Private Window. Connect to Wiki.JS.**
3. Edit an existing page, Click on Insert Assets. Navigate inside the `/test` folder. Upload an image.
4. Notice that the image is imported in the root folder.

**Comment by ethanmdavidson** [comment] 2019-10-01 12:46
It seems to only happen when you use the button with the upload icon next to the file (circled in red below). When you use the "Upload" button (circled in blue below) it seems to work as intended.
![upload](https://user-images.githubusercontent.com/1311998/65962953-bb600380-e427-11e9-808f-6e4cc7a59ceb.PNG)

**Comment by NGPixel** [comment] 2019-10-06 19:07
Fixed by 2883437a0fbb170fd8134adfd0e39e274354c1d0

**Closed by NGPixel** 2019-10-06 19:07 UTC
Labels: bug
