### ISSUE TITLE
Markdown editor automatically selecting page when adding a new link

### ISSUE THREAD

**Issue by SaasamMorgan** [Requarks/wiki#2514] opened 2020-09-29 03:11 UTC
**Describe the bug**
When adding a link on a page using the markdown editor, if you have a page which short description contains an open parenthesis "(" This will automatically select that page for any link you try to add making for a poor user experience.
This bug will only occur if there is one page which short description contains an open parenthesis. Adding another page which short description contains the same will remove the bug as the page selector will appear. If you then select a page from the list it will remove the open parenthesis.

**To Reproduce**
1. Add a page using the markdown editor. Make sure the Short Description contains an Open Parenthesis "(". Save Page.
2. Go to an existing page using the markdown editor (can be same page which we just created).
3. Add a new link my typing - [xyz](
4. Once you type the open parenthesis this will remove the open parenthesis and add the URL of the page which contains this description. the editor would now look something like [xyz]/path/to/page. when you then try to add another open parenthesis after the closing square brace to create a full link it will then add the /path/to/page again. This causes the page to look like [xyz]/path/to/page/path/to/page

**Expected behavior**
I would expect the page selector to appear with one item which is the page which contains the search values. Or not appear at all until another character is typed after the first open parenthesis.

**Screenshots**
https://imgur.com/a/Tjse15t

**Host Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Wiki.js version: 2.5.144
 - Database engine: postgresql 12.4
 - Node.JS: 14.4.0

**Comment by Igorgro** [comment] 2020-09-29 04:21
Duplicate of https://github.com/Requarks/wiki/issues/2062

**Closed** 2020-09-29 04:49 UTC
