### ISSUE TITLE
File Browser Scroll

### ISSUE THREAD

**Issue by joshuaauger** [Requarks/wiki#359] opened 2017-12-22 19:53 UTC
### Actual behavior
File Browser does not have any scrolling support
### Expected behavior
File browser/Directory tree has scrolling support
### Steps to reproduce the behavior
Have a lot of files.

**Comment by NGPixel** [comment] 2017-12-22 22:30
Duplicate of #311

**Closed by NGPixel** 2017-12-22 22:30 UTC
