### ISSUE TITLE
I accidentally deleted the interface. Is there any way to restore it?

### ISSUE THREAD

**Issue by usuiforhe** [Requarks/wiki#2728] opened 2020-11-19 10:12 UTC
I accidentally deleted the interface. Is there any way to restore it?
n order to test the deletion function, I should have deleted the new page, but I mistakenly deleted the home page.

**Comment by Smankusors** [comment] 2020-11-19 14:08
Duplicate of #2707

**Closed** 2020-11-19 16:44 UTC
Labels: help, invalid
