### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by camilodelvasto** [Requarks/wiki#168] opened 2017-07-18 18:36 UTC
### Actual behavior
Search is not working, URLs are incorrect and showing an `undefined`in the path.

### Expected behavior
URLs should load properly.

### Steps to reproduce the behavior
Go here: https://docs.requarks.io/wiki - then type anything in the search box (like `database`).

Not sure if this is a bug in the software or on the site, but I wanted to know before installing and testing it. Thanks!

**Comment by NGPixel** [comment] 2017-07-18 20:56
Duplicate of bug #161

**Closed by NGPixel** 2017-07-18 20:56 UTC
