### ISSUE TITLE
JWT allows inactive users to use wikijs

### ISSUE THREAD

**Issue by fourgates** [Requarks/wiki#900] opened 2019-07-02 21:53 UTC
**Describe the bug**
Users are still able to access permission-based content on wikijs after their `isActive` flag in the db has been set to false. This will occur if the user has a valid JWT. 

**To Reproduce**
1. Log in to wikijs
2. Set the logged in users `isActive` flag to false
3. User should still be able to view wikijs content that requires permission

**Expected behavior**
If a user is not active they should be treated as a guest. It might make sense to ensure the JWT user is active on each request. 

**Host Info (please complete the following information):**
 - OS: Windows
 - Wiki.js version: 2.0.0-beta.180
 - Database engine: MSSQL

**Comment by regevbr** [comment] 2020-06-24 06:57
@NGPixel you can close this issue as it is already fixed

**Comment by wis-ekubesh** [comment] 2020-06-24 16:22
@regevbr do you have any information when it will be available to fetch and use?

**Comment by NGPixel** [comment] 2020-06-24 16:55
@wis-ekubesh You can already achieve that by setting the token expiration to 1s under Admin > Authentication. If you ever need to ensure a user is logged out, you can invalidate the signing keys from Admin > Utilities.

The default settings are a balance of performance and security. If they don't work for you, you can change them.

**Closed by NGPixel** 2020-06-24 16:55 UTC

**Comment by wis-ekubesh** [comment] 2020-06-24 17:15
Token expiration 1s it's solution, but as you said before - it will have performance impact. 

I think solution could be tokens storage, for example - redis, where you will be able to revoke token for user.

For example if I deactivated user - all his token can be revoked  and he will be automatically logged out.
And in case when user want to terminate all his active sessions - it will be easy to implement. 

Don't you find it useful?

**Comment by regevbr** [comment] 2020-06-24 17:58
@wis-ekubesh not sure when it was enabled but you should know that JWT comes with a cost. That cost is that you can't invalidate a token immediately. 

The solution you are proposing effectively renders JWT non relevant as it also tries to solve the massive user validation costs on each request.

@NGPixel 's suggestion to reduce the token expiration will effectively achieve what you want, but as he said, with a cost.

About your issues:

1. This is indeed still an issue - I will open a new issue and fix it soon.
1. This does not happen. When the token expires, a token refresh goes on and it creates a new token with the latest permissions. If you can reproduce the issue, please open a new issue and I will fix it. You can try the following flow to see if it is a real issue:
    1. Create a user and give him some permissions
    1. Set the token expiration to something small, let's say 1 minute
    1. Log in as that user
    1. change the permissions of the user
    1. Wait until the token expires and see if the user can still use his removed permissions
1. This does not happen. When the token expires, the user info is retrieved from the DB to create a new token and if he does not exist, an error is thrown. Like (2) if you can reproduce, please open an issue and I will fix it.

**Comment by fourgates** [comment] 2020-06-24 18:06
@NGPixel 

> You can already achieve that by setting the token expiration to 1s under Admin > Authentication.

Wont this only affect new tokens? Therefore, the deactivated user would be able to access the wiki until their token expires?

> If you ever need to ensure a user is logged out, you can invalidate the signing keys from Admin > Utilities.

Won't this invalidate all user tokens? If all users would get kicked out and could potentially lose data.

**Comment by regevbr** [comment] 2020-06-24 18:08
@fourgates  You are correct on both points

**Comment by fourgates** [comment] 2020-06-24 18:29
I do like @wis-ekubesh's suggestion of using some type of cache layer to achieve what my PR did minus to performance implications. then an admin would be able to go in and refresh the cache as needed. 

A lot of organizations put sensitive information on their wiki. I do think there should be some type of advanced security here to prevent having to kick all users out and potentially causing data loss. One of the first questions asked when I pitched using wiki.js was what are the security concerns? I enjoy using wiki.js and wouldn't want this to deter others from using it.

**Comment by wis-ekubesh** [comment] 2020-06-24 19:08
My opinion is – security should be in the first place. "JWT or our JWT library doesn't support this functionality" it's not an argument when we talking about security. Redis or something like that is 100x much better and more productive than token expire time eq 1s.

**Comment by NGPixel** [comment] 2020-06-24 19:52
Keeping a list of all tokens in redis might be fast but you're adding yet another external dependency for users to install, maintain and pay for. It also defeats any advantage of using JWT in the first place.

IMO, a better solution would be to have a revocation list instead. A simple list of user IDs that must be revalidated could be kept in memory as it would only be used when changing permissions or deactivating a user. Such list could be synchronized between instances using the existing pub/sub system used for high-availability.

**Comment by NGPixel** [comment] 2020-06-24 19:54
> > You can already achieve that by setting the token expiration to 1s under Admin > Authentication.
> 
> Wont this only affect new tokens? Therefore, the deactivated user would be able to access the wiki until their token expires?

The point was to set it at 1s permanently, not only in the case of kicking out a user. By setting it to 1s, you're effectively revalidating the user access on every request.

**Comment by regevbr** [comment] 2020-06-24 20:11
> The point was to set it at 1s permanently, not only in the case of kicking out a user. By setting it to 1s, you're effectively revalidating the user access on every request.

But he is right in understanding that it will not affect current JWT tokens...

>IMO, a better solution would be to have a revocation list instead. A simple list of user IDs that must be revalidated could be kept in memory as it would only be used when changing permissions or deactivating a user. Such list could be synchronized between instances using the existing pub/sub system used for high-availability.

This can work but how do you control that list, and for how long do you keep entries in it? Over time it can potentially become a memory hog

**Comment by NGPixel** [comment] 2020-06-24 20:31
its only kept for the duration of the maximum token expiration. So if you've set 30m, it would be kept in memory for 30 mins max, as anything longer would require a token revalidation anyway. So highly unlikely to ever become more than a few items long.

**Comment by regevbr** [comment] 2020-06-24 22:37
@wis-ekubesh @fourgates do you honestly have a use case where you want to disable a user immediately and can't wait for 30 minutes until the token will be expired?
I'm sincerely interested...

**Comment by NGPixel** [comment] 2020-06-24 22:42
I could see an employee termination as a valid reason.

But considering many other systems, such as Windows / Active Directory, lets you stay logged in until you logout, this is why it's usually done preemptively.

I'll implement the revocation list feature as it addresses these concerns without impacting performance.

**Comment by regevbr** [comment] 2020-06-24 22:50
@NGPixel if you want I don't mind implementing it. Please let me know what you decide.

**Comment by NGPixel** [comment] 2020-06-25 04:06
Added in a690e5597fcfe68ab1ebc8bff7e6a61ff6417a01

**Comment by wis-ekubesh** [comment] 2020-06-25 07:23
@NGPixel Nice! There is only thing that node-cache is in-memory cache and in case when server will be reloaded - revocation list will be lost. Yeah, it's much better than before and we can set token expire ~5 min, but I think would be nice if that warning could be presented somewhere in docs.

**Comment by regevbr** [comment] 2020-06-25 07:41
Indeed that fact that it will be lost on server restart is an issue.

There are a few more issues:
1. In high availability, when a new server starts, it is not being synced with the existing list of revocation list from existing servers.
I believe we need to add a new db model to hold those revocations and the server should retrieve from it on bootstrap into the cache. If we do that, we also need to add logic to clean old revocation entries from the db.
1. I'm afraid of the revocation list of groups - if a group is changed then we recreate a proper token for the users which is great, but that means for the next 30 minutes (tokenExpiration) we will recreate the token over and over on each request for all the users in the group, which will cause calling the DB many many times... If there are many users that will create a high load on the system.
The same will happen if we assign or remove a group to a user,
I think we should maybe add a timestamp of the revocation entry creation so we can filter the actions needed if the token was created after the revocation time

@NGPixel thoughts?

**Comment by wis-ekubesh** [comment] 2020-06-25 08:32
There is the reason why I suggested to use reference tokens with store instead of self-contained.

**Comment by NGPixel** [comment] 2020-06-25 23:32
@regevbr Fixed your second point in 92b29d1f062c681046d98e4ea6bf1ca16e647f8c.

For the first point, we'll have to think of an efficient way to do it. We could ask other running instances for their list but it doesn't address the case where a server restarts. Saving the list to the DB could be done when calling the `revokeUserTokens` method but the list would need to be cleaned once in a while (e.g. via a job).

An even simpler solution IMO would be to save the timestamp when the server starts and force revalidation of any token created before that timestamp.

**Comment by NGPixel** [comment] 2020-06-26 02:07
And the restart / new instance issue fixed by 98f21b9f6a323393197c0b9023c5c332a6f67fd8

That should cover every scenario now. Let me know if you think of anything else.

**Comment by fourgates** [comment] 2020-06-26 03:15
@NGPixel Bravo! This looks like a very nice security improvement. 

Just to sum up this ticket, it now looks like a user or group is added to a `revokationList` when they get deleted and their token must be revalidated. What's going on in [98f21b9](https://github.com/Requarks/wiki/commit/98f21b9f6a323393197c0b9023c5c332a6f67fd8)? Reevaluate token if `user.iat < uRevalidate`? This is supposed to handle server restarts and high available implementations, right?

**Comment by NGPixel** [comment] 2020-06-26 03:55
No, `user.iat < uRevalidate` (line 125) validates whether the timestamp the token was issued at is before the time at which the user id was added to the revocation list. The second one (line 127) checks if the token was issued before the server was started. The third one (line 132) checks whether any of the groups the user is in was added to the list.

If any of these checks is truthy, the token must be revalidated. Afterwards, the new token will no longer match any of these checks because the timestamp is newer.

**Comment by regevbr** [comment] 2020-06-26 08:20
Awesome thanks @NGPixel
