### ISSUE TITLE
Error: Cannot find module 'qs'

### ISSUE THREAD

**Issue by bennyn** [Requarks/wiki#179] opened 2017-07-25 19:12 UTC
### Actual behavior

`Error: Cannot find module 'qs'`

### Expected behavior

No error

### Steps to reproduce the behavior

I just did `npm install wiki.js@latest` and I gave an answer to "Continue with configuration wizard?":

![screenshot](https://user-images.githubusercontent.com/469989/28589331-e4624b4a-717d-11e7-9305-e9f3a87c0c2b.png)

**Comment by NGPixel** [comment] 2017-07-25 19:37
Duplicate of #176

**Closed by NGPixel** 2017-07-25 19:37 UTC
