### ISSUE TITLE
Markdown relative links don't point to child target

### ISSUE THREAD

**Issue by dark-nova** [Requarks/wiki#1339] opened 2019-12-28 04:11 UTC
**Describe the bug**
I want to link to a relative (child) page from another page. No matter what I try, I can't link to the child page with a relative link.

**To Reproduce**
1. Go to a page, e.g. `example.com/en/a`.
2. Edit the page to create a Markdown link like `[b](a/b)`, which worked in v1.
3. `[b](a/b)` actually points to `example.com/en/a/a/b` in the current stable.
4. `[b](./b)` predictably points to `example.com/en/b` as it also did in v1, but that's not the problem here.

**Expected behavior**
If step 4 is expected behavior (which also could be suspect here, as I would expect `./b` notation to point to the child, like in a Linux filesystem), step 3 should not create another pseudo-directory (with the same name as the parent) between the original parent and the target child.

**Screenshots**

**Host Info (please complete the following information):**
 - OS: Lubuntu 18.04, Docker
 - Wiki.js version: 2.0.12
 - Database engine: Postgres 11

**Additional context**
I can somewhat sidestep this issue by doing `[b](../a/b)` but this might break locales (?).

I appreciate the updates on Wiki.js!

**Comment by NGPixel** [comment] 2019-12-28 08:10
Duplicate of #1201

**Closed by NGPixel** 2019-12-28 08:10 UTC

**Comment by deem0n** [comment] 2020-01-30 17:26
Related to the bug: In the Markdown preview links are rendered differently from the normal page.

When you edit page `/e/ru/luxarch/biserver` and have markdown like this:

```
[1](nginx)
[2](../nginx)
[3](/luxarch/nginx)
```

You get these in preview:

```
/e/ru/luxarch/nginx
/e/ru/nginx
/luxarch/nginx
```

When you see final page at `/ru/luxarch/biserver` you got

```
/ru/luxarch/biserver/nginx
/ru/nginx
/ru/luxarch/nginx
```

which is very confusing!
