### ISSUE TITLE
TOC with UTF8 charactors error: display & click

### ISSUE THREAD

**Issue by fanlix** [Requarks/wiki#1976] opened 2020-06-01 10:24 UTC
**Describe the bug**
if write UTF-8 words in H1 and H2, then <kbd>Table of Contents</kbd> tree goes error.
* utf-8 charactors displays: 口x口?x
* anchor click: no jump effect

**To Reproduce**
```
## english works
## china 中文
## japan きんぎょ
## korea 송별연
```

**Host Info (please complete the following information):**
 - OS & wikijs: 
   - `docker= beta-arm: 0576f8903663`
 - Browser:
   - Chrome, Edge, Firefox

**Advice**
the <kbd>href</kbd> should set charset to utf-8 or escaped

**Comment by he110** [comment] 2020-06-01 12:37
Have the same issue with requarks/wiki:beta.
Cyrillic characters displays like: ÐÐ¿Ð¸ÑÐ°Ð½Ð¸Ðµ Ð²ÐµÑÐ²ÐµÐ¹

**Comment by Smankusors** [comment] 2020-06-01 13:20
Duplicate of #1971

**Closed** 2020-06-01 14:26 UTC
