### ISSUE TITLE
Error when going to view full history

### ISSUE THREAD

**Issue by depict1** [Requarks/wiki#1648] opened 2020-03-31 13:59 UTC
**Describe the bug**
Error when going to view full history

**To Reproduce**
1. https://wiki.X.to/a/pages/n (n being a number)
2. Click VIEW FULL HISTORY
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/57202889/78034682-aa884000-732d-11ea-89f0-14ceabcf8df9.png)
![image](https://user-images.githubusercontent.com/57202889/78034746-bf64d380-732d-11ea-9b93-5b3b5ac3ecfc.png)

**Host Info (please complete the following information):**
2.50

**Comment by Smankusors** [comment] 2020-03-31 14:54
your host info is incomplete, please complete that

**Comment by NGPixel** [comment] 2020-04-01 00:30
Closing as it's caused by #1649

**Closed by NGPixel** 2020-04-01 00:30 UTC
