### ISSUE TITLE
GraphQL really slow respond time (with Chrome)

### ISSUE THREAD

**Issue by maka1000** [Requarks/wiki#1611] opened 2020-03-23 04:51 UTC
Hi

### Actual behavior
When I log in Admin backend and select a menu item, it load really slow. So it need around 15 seconds, till grapql is answering. (see attached screenshot). I use Chrome Version 80.0.3987.149 (64bit), With Firefox it is working without any problem.

![Printscreen](https://user-images.githubusercontent.com/19875641/77282412-2220f400-6cca-11ea-97e2-6edec36a810d.png)

### Expected behavior
I expect fast loading times.

### Steps to reproduce the behavior
Do the same like descripted in "Actual behavior".

**Comment by Smankusors** [comment] 2020-03-23 08:47
what is the respond time when you use Chrome in incognito?

**Comment by maka1000** [comment] 2020-03-23 09:14
it is same respond time.

**Comment by Smankusors** [comment] 2020-03-23 14:32
hmm can you try with different people/profile on your Google Chrome? Or perhaps you can try with Guest profile?

**Comment by NGPixel** [comment] 2020-03-28 00:43
If it works fine in Firefox but not Chrome, then you must have some extension causing this issue or a broken network configuration. It's highly unlikely the issue is with Wiki.js itself.

**Comment by maka1000** [comment] 2020-04-08 12:49
Ok, I think i have found the issue: It must be a problem with my loadbalancer, because when i turn off one, then it is fast how it should. So it don't have something to do with wikijs.
Thanks for your help anyway.

**Comment by Smankusors** [comment] 2020-04-08 13:20
Since it's resolved, can you close the issue? :)

**Closed** 2020-04-08 14:02 UTC
Labels: help
