### ISSUE TITLE
Code block: line wrap if too long

### ISSUE THREAD

**Issue by Selven99** [Requarks/wiki#1079] opened 2019-10-01 14:40 UTC
Hi,
I found an issue on my wiki instance (beta-303): if you have a too long line in a code block, so this line will be wrapped in strangely on front.

Example for a pentest :
**\`\`\`shell
sqlmap -u "a.sample.http.server/catalog/product_frontend_action/synchronize?type_id=recently_products&ids[0][added_at]=&ids[0][product_id][from]=?&ids[0][product_id][to]=))) OR 1=1-- -" -D magento -T core_config_data -C path,value --dump
\`\`\`**

In fact, there is **only one line** and preview on the right is fine.
On front when I go the the page, I get:
![Screenshot-2019-10-1 CTF Pmanset](https://user-images.githubusercontent.com/11805144/65972234-d6536780-e469-11e9-8c75-4f9036463aa7.png)

Do you have any idea?

Thanks for your help!

**Comment by jimmybrancaccio** [comment] 2019-10-23 16:51
I can confirm it looks like this is happening in RC1 as well.

**Comment by juliendms** [comment] 2019-11-21 14:37
Workaround: add this in the CSS override in the Theme of the Admin part
```css
.contents .prismjs {
	white-space:pre-wrap;
}
```

**Comment by NGPixel** [comment] 2019-11-22 21:18
Fixed by a72a7b1cdfc70fa87f861d4bd39a5f257bfc61e1

**Closed by NGPixel** 2019-11-22 21:18 UTC
Labels: bug
