### ISSUE TITLE
Entire left sidebar not visible on <980px width

### ISSUE THREAD

**Issue by colinmollenhour** [Requarks/wiki#390] opened 2018-01-31 23:28 UTC
### Actual behavior

Entire left sidebar not accessible on narrow screens

### Expected behavior

Menu should somehow be accessible, such as with "hamburger" button to expand.

### Steps to reproduce the behavior

Resize your browser window to be more narrow than 980px. Now you cannot navigate, access settings, etc.

**Comment by NGPixel** [comment] 2018-02-03 01:18
Duplicate of #103 

Non-desktop resolutions will be supported in 2.0.

**Closed by NGPixel** 2018-02-03 01:18 UTC
