### ISSUE TITLE
WikiJS returns error when try to edit page

### ISSUE THREAD

**Issue by hallo1142** [Requarks/wiki#2398] opened 2020-09-08 16:10 UTC
**Describe the bug**
When I try to edit a page an error gets thrown in console and the page returns an timeout.

**To Reproduce**
1. Click on Edit on a page
2. Check Console

**Expected behavior**
The editor opens to edit the page.

**Screenshots**
[Image](https://image.sv-studios.net/39bb47d1570983c55e88419672c08989d.png)

**Host Info (please complete the following information):**
 - OS: Debian 8
 - Wiki.js version: 2.5.126
 - Database engine: MySQL 8

**Comment by NGPixel** [comment] 2020-09-08 16:12
Duplicate of #2374

**Closed by NGPixel** 2020-09-08 16:12 UTC
