### ISSUE TITLE
Search function seem does not to work occasionally

### ISSUE THREAD

**Issue by zhinuok** [Requarks/wiki#1455] opened 2020-02-09 13:52 UTC
**Describe the bug**
At present it seems that there are still some problems with the search function, especially for Chinese search, often the target cannot be found. Is it possible to improve the search function in the near future?

**Screenshots**
![image](https://user-images.githubusercontent.com/55477397/74103304-164bf900-4b86-11ea-9264-d814ad836720.png)
**Host Info (please complete the following information):**
 - OS: CentOS 7, Docker
 - Wiki.js version: 2.0.1
 - Database engine: postgres 11

**Comment by NGPixel** [comment] 2020-02-09 19:15
Duplicate of #1404

**Closed by NGPixel** 2020-02-09 19:15 UTC
