### ISSUE TITLE
Can't exit out of file browser when uploading

### ISSUE THREAD

**Issue by StevenH001** [Requarks/wiki#64] opened 2017-04-12 14:19 UTC
When uploading an image or file in MS Edge, if you try to hit cancel on the file browser, it will close for a second and then immediately re-open. I have to attempt to upload a file and then just discard it to get it to go away.

**Comment by NGPixel** [comment] 2017-05-04 23:36
Can't reproduce anymore. Looks like it was fixed by a package update or a recent MS Edge update.

Re-open this ticket if you still experience this bug with the latest release and on the latest update of W10.

**Closed by NGPixel** 2017-05-04 23:36 UTC
Labels: wontfix
