### ISSUE TITLE
GraphQL SQL Error

### ISSUE THREAD

**Issue by andrewogden1678** [Requarks/wiki#2423] opened 2020-09-11 02:26 UTC
Hi! Having a few issues with media assets. I can't do anything related to assets because I receive a GraphQL SQL exception every time. Here is a screenshot, it occurs whenever I try and do anything asset-related. I was using MySQL, but even after migrating to PostgreSQL, I get the same error.
![image](https://user-images.githubusercontent.com/31175571/92844886-b07c6400-f429-11ea-8519-f6803a3e2b0b.png)

**Host Info (please complete the following information):**
OS: Ubuntu 18.04
Wiki.js version: 2.5.126
Database engine: observed with MySQL 5.7.8 & Postgre 12.4

**Comment by Smankusors** [comment] 2020-09-11 05:08
Duplicate of #2149

**Closed** 2020-09-11 21:43 UTC
Labels: help
