### ISSUE TITLE
plantuml  diagrams failing to render

### ISSUE THREAD

**Issue by bobjolliffe** [Requarks/wiki#1919] opened 2020-05-22 10:44 UTC
**Describe the bug**
Rendering plantuml is failing with :

"the plugin you are using seems to generated a bad url"

I think that this may be resulting from a change in the plantuml api.

**To Reproduce**
Enter any plantuml diagram with:

```plantuml
....
```

see the resulting error image

**Expected behavior**
To see the plantuml diagram

**Screenshots**
![image](https://user-images.githubusercontent.com/1135531/82660526-7260f780-9c22-11ea-8ede-facf8d628485.png)

**Host Info (please complete the following information):**
 - OS: Ubuntu 20.04, Docker
 - Wiki.js version: 2.3.81

**Comment by Smankusors** [comment] 2020-05-22 12:26
Duplicate of #1857

**Closed** 2020-05-22 12:32 UTC
