### ISSUE TITLE
Cannot raise user to admin level or admin level permissions

### ISSUE THREAD

**Issue by lambdabetaeta** [Requarks/wiki#2430] opened 2020-09-12 15:10 UTC
As Administrator, using the Groups panel does not allow giving administrator privileges to another user.

In particular, when editing the Group if I click "Assign User" and pick a user, I get the error

> GraphQL error: You are not authorized to assign a user to this elevated group.

Similarly, when logged in as Administrator I cannot give any non-content permissions to any non-administrator user. Checking any user or admin permission gives the error message

> You are not authorized to manage this group or assign these permissions.

The installation is that given out-of-the-box by a [DigitalOcean droplet](https://marketplace.digitalocean.com/apps/wiki-js).

In my case it applies to version 2.5.132 (Node.js version 14.10.0, PostgreSQL 11.8).

**Comment by NGPixel** [comment] 2020-09-12 18:07
Duplicate of #2424

**Closed by NGPixel** 2020-09-12 18:07 UTC
