### ISSUE TITLE
Daily backup does not run

### ISSUE THREAD

**Issue by ghost** [Requarks/wiki#1714] opened 2020-04-14 02:09 UTC
**Describe the bug**
When setting the "Create Daily Backups" to on in the Local File System option under Storage, no backups get created. The _daily folder does not appear at the specified location either. The manual backups do work and are created inside the "_manual" folder at the specified location.

**To Reproduce**
1. Go to the Administration area
2. Click on "Storage"
3. Select "Local File System"
4. Enter a path where you would like to have data saved to.
5. Turn on "Create Daily Backups"
6. Click "Apply"
7. Wait 24 hours (At what time is the backup supposed to occur?)
8. Look in the defined file system location. No "_daily" folder was created.

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04, Docker
 - Wiki.js version: 2.2.51
 - Database engine: SQLite

**Comment by NGPixel** [comment] 2020-04-24 04:38
Fixed by bade9430f206aa819919f9c9a0f41040fde7985b

**Closed by NGPixel** 2020-04-24 04:38 UTC

**Comment by pelijaro** [comment] 2024-01-19 12:24
Hello,

I am having the same problem, I have activated the daily backup but it is not being performed even so the module works fine because when I create or delete a file this is created or deleted from the directory but the daily backup does not appear that by the way, what time it runs?

To Reproduce
Steps to reproduce the behavior:

Go to the Administration area
Click on "Storage"
Select "Local File System"
Enter a path where you would like to have data saved to.
Turn on "Create Daily Backups"
Click "Apply"
Wait 24 hours (At what time is the backup supposed to occur?)
Look in the defined file system location. No "_daily" folder was created.
Host Info (please complete the following information):

OS: Docker
Wiki.js version: 2.5.300
Database engine:  PostgreSQL
