### ISSUE TITLE
User email cannot be updated

### ISSUE THREAD

**Issue by tiagohillebrandt** [Requarks/wiki#626] opened 2018-09-05 15:33 UTC
### Actual behavior
When you are a Global Administrator, you should be allowed to update users email.

However, today if you update the email address from any users, and then hit the save button, it says the "Changes have been applied successfully" however the email address is not really updated.

Version: 1.0.102

### Expected behavior
When a new email is provided when editing the user, the email address should be updated to the one provided.

### Steps to reproduce the behavior

1. Login with a `Global Administrator` user.
2. Click over Settings > Users.
3. Create an user with Read only access.
4. Edit this new user and update the user's email.
5. Hit the `Save Changes` button. The `Changes have been applied successfully` message will be displayed.
6. If you access the Users screen again, you will see that email was not updated.

**Comment by linkdragon70** [comment] 2018-09-05 19:59
I have the same problem, as an alternative, I delete and recreate the user. But I did not open an issue, so I'm curious to know what the solution would be.

**Comment by NGPixel** [comment] 2018-09-06 23:34
Duplicate of #349

**Closed by NGPixel** 2018-09-06 23:34 UTC
