### ISSUE TITLE
Algolia prevents indexing on big documents

### ISSUE THREAD

**Issue by jayzalowitz** [Requarks/wiki#2089] opened 2020-06-20 01:27 UTC
**Describe the bug**
When you have a large document this gets thrown and no documents get indexed:
https://github.com/Requarks/wiki/blob/master/server/modules/search/algolia/engine.js#L142

**To Reproduce**
Make a very large document

**Expected behavior**
At least some documents would get through

**Additional context**
https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/how-to/indexing-long-documents/ splitting by line would work just as well for these documents. At the very least telling what document was causing the problem would be great while trying to rebuild index.

**Comment by NGPixel** [comment] 2020-06-26 19:41
Duplicate of #1833

**Closed by NGPixel** 2020-06-26 19:41 UTC
Labels: duplicate
