### ISSUE TITLE
Local Login returns "Invalid Authentication Provider"

### ISSUE THREAD

**Issue by josh-hemphill** [Requarks/wiki#1978] opened 2020-06-01 19:33 UTC
**Describe the bug**
I was setting up LDAP authentication, when I tried to save a new edit to the config it threw a "not authorized" error, so I logged out assuming that updating the authentication meant I would need to re authenticate. 
It now shows LDAP as an option (though it doesn't work, since our LDAP setup is very finicky and hard to connect to; I don't expect that to be working the first few tries) but the Local login seems to be broken preventing me from logging in with the admin account. 

**To Reproduce**
In a fresh Docker environment.
1. Go to 'Administration'
2. Click on 'Authentication'
3. Scroll down and click on 'LDAP'
4. Set up a bad LDAP config that shouldn't result in a successful connection.
5. Save the config.
6. Attempt to change the config again.
6. Attempt to save the change.
[Observe first error here.]
8. Log out
9. Click on "Local" auth option
10. Attempt to login with Admin credentials 

**Expected behavior**
To log in with the admin credentials

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: ^2
 - Database engine: postgres: latest

**Additional context**
Since I'm pretty sure my LDAP config is incorrect, it is likely an LDAP auth or SSL protocol error that caused all of this. The LDAP is probably using an SSL cipher that is not supported by the Alpine Linux container Wiki.js is running in.
But I would hope that error wouldn't result in the Administrator getting locked out.

**Comment by NGPixel** [comment] 2020-06-02 01:21
Fixed by 2013ee4fa251b0a423c835da41913a41e6d55812

The issue is you enabled TLS but its unable to open the certificate file you specified (missing or incorrect path).

**Closed by NGPixel** 2020-06-02 01:21 UTC
