### ISSUE TITLE
Pressing Shift+( after ] inserts partial page path

### ISSUE THREAD

**Issue by fireundubh** [Requarks/wiki#2134] opened 2020-07-03 06:15 UTC
When I press `Shift+(` after the `]` character, a partial page path is inserted. In my case, the path to the page with ID 8 is inserted.

![2020-07-02 23_04_53](https://user-images.githubusercontent.com/1261664/86437258-fb0a9300-bcb8-11ea-8689-c391126c9357.jpg)

![2020-07-02 23_05_07](https://user-images.githubusercontent.com/1261664/86437267-fe9e1a00-bcb8-11ea-8706-742c9839e237.jpg)

This makes creating Markdown links tedious. Not sure what's going on, but this has been happening for many past versions.

**Host Info (please complete the following information):**
 - OS: Linux - Ubuntu (artful) 17.10 x64
 - Wiki.js version: 2.4.107
 - Database engine: 10.4.12-MariaDB-1:10.4.12+maria~xenial-log

**Comment by fireundubh** [comment] 2020-07-03 06:19
In my case, the page at ID 8 is the first available page when I open the Insert Link dialog.

![2020-07-02 23_16_41](https://user-images.githubusercontent.com/1261664/86437896-58531400-bcba-11ea-92ee-899369431198.jpg)

**Comment by tionis** [comment] 2020-07-25 19:58
I also encountered this bug a few times.

**Comment by peteruithoven** [comment] 2020-09-09 16:41
I think this is a duplicate of: https://github.com/Requarks/wiki/issues/2062
Would be good to re-post some of these more technical details to that issue?

**Closed** 2020-09-13 20:35 UTC
