### ISSUE TITLE
Vertical-navigation-drawer behavior (bug or feature?)

### ISSUE THREAD

**Issue by vincent-polite** [Requarks/wiki#1535] opened 2020-02-26 22:56 UTC
**Describe the bug**
At desktop widths/fullscreen, the navigation drawer appears over text on a new page load.  I wouldn't mind this behavior if the drawer "pushed" the content so it was all visible.  However, this creates an unnecessary step everytime you use the navigation where you have to explicitly close the navigation.

I tried finding the source code in my node deployment; I'm only doing node run server to access the wiki, so I'm not sure where I might affect change, but I'd prefer behavior where once I use a navigation link, I'm viewing the content of what I navigated to.  Any further link hopping I would expect to bring the navigation up again.

I know the vertical navigation drawer control has options and apparently those options are hardcoded.  Maybe some folks like the way it works, but the autohide on mobile dimensions makes sense at all dimensions; while the argument can be made for "always on navigation", I only get the benefit if I am also able to see all the content.  Is there anything I can do either on my own instance or as a fix to the core project to update this behavior?

**To Reproduce**
1.  Set up navigation links in the Administration section
2.  Upsize your viewport to full screen on a standard HD monitor (1920px wide?)
3.  Click on a navigation link
4.  When you are on a new page, you will see the navigation menu again, covering the content to the point where depending on the content, you don't actually know if you've moved or not.

**Expected behavior**
1.  Clicking on navigation sends you to a page where the navigation is auto-hidden.
2.  If navigation must be shown; would prefer an option to have nav PUSH content over to the right.
3.  Other concepts such as "pinning" the navigation so it's always on make sense as well, but I'd settle for 1.

**Host Info (please complete the following information):**
 - OS: Windows 2019
 - Wiki.js version: 2.1.113
 - Database engine: mssql 2019

**Additional context**

**Comment by NGPixel** [comment] 2020-02-27 06:22
You're not supposed to see the navigation drawer shown as an overlay when browsing on desktop. This is a bug that only happens to a small percentage of users, which makes it hard to fix. The viewport breakpoints will be reduced in the next update to mitigate this issue.

**Comment by NGPixel** [comment] 2020-02-27 06:23
Duplicate of #1341

**Closed by NGPixel** 2020-02-27 06:23 UTC
