### ISSUE TITLE
page web within the markdown page

### ISSUE THREAD

**Issue by pirvana** [Requarks/wiki#1305] opened 2019-12-12 12:16 UTC
**Question**

Good, a query, before the update 2.0.12, when making the code 

```
<object data="https://access.redhat.com/solutions/3025421" type="" align="center" width="100%" style="height:9999px">
</object>
```

 showed the website, and currently with the same code no longer shows me anything, just a white background, there would be another way to integrate a page web within the markdown page

**Host Info (please complete the following information):**
OS: [e.g. Centos 7, Docker]
Wiki.js version: [e.g. 2.0.12]
Database engine: [e.g. postgres 9.7]

**Comment by ssimontis** [comment] 2019-12-31 13:09
The HTML renderer responsible for whitelisting HTML tags for display no longer allows the <object> tag to be used on a site. You can see a list of all allowed tags under server/rendering/html-security/renderer.js.

**Comment by ssimontis** [comment] 2019-12-31 13:10
@NGPixel can we please close this one out since it is working as intended?

**Closed** 2021-03-21 00:52 UTC
Labels: help
