### ISSUE TITLE
Firefox breaking visual editor / glitches.

### ISSUE THREAD

**Issue by kommandantjut** [Requarks/wiki#2845] opened 2020-12-20 16:59 UTC
**Describe the bug**
When one goes to edit an article in the visual editor after a few moments of typing or moving stuff around the visual editor will freeze and you cannot backspace or continue to format as the issue progressing it will prevent you from even typing.
I thought this was an overall issue but I tried editing on safari and I didn't seem to have this issue, I was only able to reproduce it on my firefox client.

**To Reproduce**
1.) Use visual editor and firefox.

**Expected behavior**
You should be able to fully edit articles without issue.

**Screenshots**
N/A

**Host Info (please complete the following information):**
OS: CentOS Linux release 7.8.2003 (Core)
Wiki.js version: 2.5.170
Database engine: 10.3.23-MariaDB - MariaDB Server

**Comment by NGPixel** [comment] 2020-12-20 19:01
Duplicate of #2758

**Closed by NGPixel** 2020-12-20 19:01 UTC
