### ISSUE TITLE
Slashes in automatic commit messages are not properly displayed

### ISSUE THREAD

**Issue by bennyn** [Requarks/wiki#209] opened 2017-08-17 06:00 UTC
I am using the GitHub sync and the automatic commit messages write things like these:

- `Updated curriculum&#x2F;mongodb.md`

But the commit message should look like:

- `Updated curriculum/mongodb.md`

**Screenshot**

![Screenshot](https://user-images.githubusercontent.com/469989/29397999-2b0e4dd6-8322-11e7-8640-f46e1b31bd77.PNG)

**Comment by NGPixel** [comment] 2017-08-17 17:54
Duplicate of #185

**Closed by NGPixel** 2017-08-17 17:54 UTC
Labels: duplicate
