### ISSUE TITLE
Wiki.js behind corporate web proxy

### ISSUE THREAD

**Issue by aaronstuder** [Requarks/wiki#2227] opened 2020-07-24 16:34 UTC
Any ideas on how to get this working?

Here is the errors:

```
2020-07-24T16:32:50.860Z [MASTER] error: Fetching latest updates from Graph endpoint: [ FAILED ],
2020-07-24T16:32:50.861Z [MASTER] error: request to https://graph.requarks.io failed, reason: connect ECONNREFUSED 104.26.14.122:443,
2020-07-24T16:32:50.862Z [MASTER] error: Syncing locales with Graph endpoint: [ FAILED ],
2020-07-24T16:32:50.863Z [MASTER] error: request to https://graph.requarks.io failed, reason: connect ECONNREFUSED 
```

**Comment by aaronstuder** [comment] 2020-07-24 16:37
I see some headway was made here, but it doesn't seem to be a supported way to do it.

https://github.com/Requarks/wiki/issues/1190

**Comment by Smankusors** [comment] 2020-07-25 18:59
It's planned on [here](https://wiki.js.org/feedback/p/enable-http-proxy-use).

But unfortunately it looks like it's not the priority now. 😟

**Comment by aaronstuder** [comment] 2020-07-25 19:04
I was hoping to find some sort of workaround until it's been implemented.

**Comment by NGPixel** [comment] 2020-07-25 19:06
Duplicate of #1190

Follow https://wiki.js.org/feedback/p/enable-http-proxy-use

**Closed by NGPixel** 2020-07-25 19:06 UTC
Labels: help
