### ISSUE TITLE
Errorneous HTML code block syntax highlighting in markdown editor

### ISSUE THREAD

**Issue by despens** [Requarks/wiki#1258] opened 2019-11-24 15:27 UTC
**Describe the bug**
Code blocks with HTML, aren't rendered correctly in markdown editor preview.

**To Reproduce**
1. create a new markdown page
2. create a HTML code block (starting with ```html) and enter some HTML code

**Expected behavior**
The preview should render the HTML code block

**Screenshots**
![image](https://user-images.githubusercontent.com/571494/69496866-1ae20900-0ed7-11ea-8ab1-d2c428ec7e14.png)

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04, Docker
 - Wiki.js version: 2.0.12
 - Database engine: Postgres 11

**Comment by despens** [comment] 2019-11-24 17:35
Probably connected with #1257, Apache config uses XML-like syntax elements, too.

**Comment by NGPixel** [comment] 2019-11-24 17:44
Duplicate of #1257

**Closed by NGPixel** 2019-11-24 17:44 UTC
