### ISSUE TITLE
Error when deleting images

### ISSUE THREAD

**Issue by depict1** [Requarks/wiki#1737] opened 2020-04-17 15:44 UTC
**Describe the bug**
If you click the ... to delete an image you will get image 1 below. It looks like you need to click the actual image THEN click the ... to delete it. See image 2.

See image 3. Say there is 5 images. You click on image 3. You then click the ... of image 2 and press delete. The dialogue box that pops up will delete image 3 NOT image 2.

**To Reproduce**
Above.

**Expected behavior**
Click ... and delete images. Click ... no matter what image/asset you have selected to delete that image, not the image you have selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/57202889/79587339-083fba80-8098-11ea-8beb-f563354faf37.png)
Image 1 above.

![image](https://user-images.githubusercontent.com/57202889/79587381-14c41300-8098-11ea-92b9-cd5507f32393.png)
Image 2 above.

![image](https://user-images.githubusercontent.com/57202889/79587407-1ee61180-8098-11ea-84d4-e20aebbccedf.png)
Image 3 above.

**Host Info (please complete the following information):**
docker-compose
ubuntu

**Comment by depict1** [comment] 2020-04-17 16:01
My image 3 might be a visual glitch and it does indeed delete the image that you click the ... of despite it saying the name of the image you have selected.

**Comment by Smankusors** [comment] 2020-04-17 16:42
duplicate of #1518 and #1493

**Closed** 2020-04-17 16:56 UTC
Labels: duplicate
