### ISSUE TITLE
Blockquotes with Unordered Lists

### ISSUE THREAD

**Issue by sbonaime** [requarks/wiki#1505] opened 2020-02-20 09:59 UTC
It is possible to use unordered lists with blockquote

But it is not possible with styling (is-info, is-success, is-warning and is-danger) 

If a  dash symbol whitespace follow a greater-than symbole, then the styling does not apply. Even if there is only one line starting with a dash symbol, the styling is ignored for the whole blockquote

![Capture d’écran 2020-02-20 à 20-02-20 11 01 18](https://user-images.githubusercontent.com/750709/74923005-5c982800-53d0-11ea-91be-9ce1be8b0227.png)

**Comment by juliendms** [comment] 2020-03-11 12:02
Duplicate of #1241

**Comment by MooshuBeef** [comment] 2021-01-11 06:52
Glad to see I wasn't the only one who wants this! Attaching a situation where somehow by the order of me typing the list then adding the dashes in later... I was somehow able to get an unordered list working with styling of `.is-info`. For the top part of the list (under Winners Bracket):

![image](https://user-images.githubusercontent.com/27934886/104153081-41425c80-5396-11eb-9b57-8e2e720009a7.png)

Then once I add even one dash for the lower part of the list, the formatting of an info blockquote it loses the formatting:
![image](https://user-images.githubusercontent.com/27934886/104153202-941c1400-5396-11eb-9dba-cf1c3d34d3a5.png)

**Comment by NGPixel** [comment] 2023-06-03 07:46
This was addressed back in 2.5.291 by the inclusion of markdown-it-decorate.

You must use the following syntax to specify which element should receive the class:

```markdown
> - a
> - b
> - c
<!-- {blockquote:.is-info} -->
```

**Closed by NGPixel** 2023-06-03 07:46 UTC
Labels: bug, contrib-medium
