### ISSUE TITLE
Page rendering stripped up <style> tag 

### ISSUE THREAD

**Issue by Jaeha90** [Requarks/wiki#1352] opened 2020-01-03 11:30 UTC
**Describe the bug**
When including a <style> tag in a  page edited with markdown, the resulting HTML page stripped up the <style> tag.

Here is the rendering during the page editing (Which is totally fine) :
![image](https://user-images.githubusercontent.com/7950262/71720891-7e8b1a80-2e23-11ea-9f25-25fe69bf040a.png)

And here is the rendering on the page in view mode :
![image](https://user-images.githubusercontent.com/7950262/71720973-babe7b00-2e23-11ea-8825-df951418508a.png)

When I inspect the html, I can see the <style> tag has been stripped up from the page.
I have investigate a little bit more, and if I check the database for this page, I can see the <style> tag is already stripped up from the render column in pages table :
![image](https://user-images.githubusercontent.com/7950262/71721287-cb232580-2e24-11ea-9ae1-0238e45207d2.png)

Am I missing something ? Knowing that Html is allowed in Markdown rendering configuration.

Thank you

**Comment by mielipuolinen** [comment] 2020-01-18 21:38
Run into this issue as well. Here's my report about it too.

**Describe the bug**
HTML style-tags are being stripped from Markdown pages which makes page customization more difficult.

**To Reproduce**
Steps to reproduce the behavior:
1. Create an empty page with markdown editor
2. Add <style></style> tags into page with some CSS content.
3. Save and view page source to confirm that style tags are stripped

**Expected behavior**
Style-tags not to be stripped.

**Screenshots**

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04, up-to-date unmodified docker compose file
 - Wiki.js version: 2.0.12
 - Database engine: PostgreSQL 11.6

**Additional context**
Same behavior is with script-tags which could be useful too for interactive pages (e.g. complex tables). 
Obviously for script-tags you would want to trust your users before allowing them to use those.

**Comment by mielipuolinen** [comment] 2020-01-18 21:40
@NGPixel Could you take a look at this if possible? Noticed this one was missing an assignee. 
Cheers!

**Comment by Smankusors** [comment] 2020-02-10 16:05
there's warning on Vue if you attempt to use `style` tag inside page.

```
vue.esm.js:629 [Vue warn]: Error compiling template:

Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <style>, as they will not be parsed.
```

so.... this is become more complicated than I think 😕

**Comment by regevbr** [comment] 2020-05-31 09:35
In latest release the style element is not stripped but is rendered as plain text. (after enabling html tags in the render settings)
![image](https://user-images.githubusercontent.com/5775519/83348579-c2347280-a336-11ea-9317-470eb760d2e5.png)

![image](https://user-images.githubusercontent.com/5775519/83348575-b9dc3780-a336-11ea-94a5-8894188dc5f3.png)

When testing the same on the master branch, the issue is fixed. @NGPixel can you confirm that it means it will be fixed in the next release?

It seems that it was fixed due to the changes in the master branch on the html-security render module

p.s
Trying in the `latest` branch the issue still persists

**Comment by regevbr** [comment] 2020-05-31 09:41
Actually on master the style element just disappears... so the issue is not really fixed. I will try to create a PR by end of day

**Comment by regevbr** [comment] 2020-05-31 09:57
I manged to fix it locally based on the solution [here](https://stackoverflow.com/a/57331310/2242402):
in the html render we need to replace the style tags with component:
```javascript
    output = output.replace(/<style/g, `<component is="style"`);
    output = output.replace(/<\/style>/g, `</component>`);
```

**Comment by NGPixel** [comment] 2020-06-20 21:53
Added in 2.5.

**Closed by NGPixel** 2020-06-20 21:53 UTC
Labels: bug, contrib-easy
