### ISSUE TITLE
PostgreSQL error on Google Auth

### ISSUE THREAD

**Issue by oleg-raev** [Requarks/wiki#1375] opened 2020-01-14 15:24 UTC
### Actual behavior
I've setup Google Auth for authentification. Then I tried to login using it, but got error
![image](https://user-images.githubusercontent.com/4128450/72356695-ba16c600-36fa-11ea-8801-5de69c1b2599.png)

> Oops, something went wrong...insert into "users" ("createdAt", "email", "isActive", "isSystem", "isVerified", "localeCode", "name", "pictureUrl", "providerId", "providerKey", "tfaIsActive", "updatedAt") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) returning "id" - value too long for type character varying(255)

Same as described in https://github.com/Requarks/wiki/issues/876, but for Google Auth

### Expected behavior
I can sign up and login using Google account credentials

### Steps to reproduce the behavior
1. Go to login page
2. Click on Google button

### Environment
- WikiJS: 2.0.12
- PostgreSQL: 11.6
- NodeJS: 10.16.3

**Comment by NGPixel** [comment] 2020-01-15 02:39
Duplicate of #1311

**Closed by NGPixel** 2020-01-15 02:39 UTC
