### ISSUE TITLE
Unable to upload the second picture

### ISSUE THREAD

**Issue by lacatc** [Requarks/wiki#551] opened 2018-06-21 01:34 UTC
Unable to upload the second picture: After uploading the first picture, there will be errors when uploading other pictures. You need to save the file before editing.
![image](https://user-images.githubusercontent.com/37959871/41693051-147ef3a2-7536-11e8-844d-571d9cd7117f.png)

**Comment by NGPixel** [comment] 2018-06-22 17:04
Duplicate of #265

**Closed by NGPixel** 2018-06-22 17:04 UTC
