### ISSUE TITLE
Administration->General gives "siteHost.splice is not a function"

### ISSUE THREAD

**Issue by choongwh** [Requarks/wiki#1946] opened 2020-05-28 02:29 UTC
**siteHost.splice is not a function**
Was given when trying to change the Administration->General. 
Cannot click the APPLY button. 
The website will not saved. And gave the error...
"siteHost.splice is not a function"

On the Admistration Area, without changing anything, Clicking the APPLY, will gives this error.

**Comment by choongwh** [comment] 2020-05-28 02:32
![image](https://user-images.githubusercontent.com/65994910/83091719-6cf62800-a0ce-11ea-82d5-6a556e228326.png)

When clicking the APPLY button, the box appears with "siteHost.splice is not a function" and nothing saved. 
Without changing anything, it just refuses to save. 
Tried on different computers, still give same result.

**Comment by choongwh** [comment] 2020-05-28 04:07
app.3db9914c6708a1a6227a.js:2 [GraphQL error]: Message: siteHost.splice is not a function, Location: [object Object], Path: site,updateConfig

/*! Wiki.js - wiki.js.org - Licensed under AGPL */
(this.webpackJsonp=this.webpackJsonp||[]).push([["app"],{"./client/client-app.js":function(e,t,n){"use strict";n.r(t),function(e){var t=n("./node_modules/vue/dist/vue.esm.js"),i=n("./node_modules/vue-router/dist/vue-router.common.js"),r=n.n(i),o=n("./node_modules/vue-clipboards/dist/vue-clipboards.js"),a=n.n(o),s=n("./node_modules/apollo-client/bundle.umd.js"),l=n("./node_modules/apollo-link-batch-http/lib/index.js"),c=n("./node_modules/apollo-link/lib/index.js"),d=n("./node_modules/apollo-link-ws/lib/index.js"),u=n("./node_modules/apollo-link-error/lib/index.js"),p=n("./node_modules/apollo-cache-inmemory/lib/bundle.cjs.js"),m=n("./node_modules/apollo-utilities/lib/bundle.cjs.js"),f=n("./node_modules/vue-apollo/dist/vue-apollo.umd.js"),h=n.n(f),v=n("./node_modules/vuetify/lib/framework.js"),g=n("./node_modules/velocity-animate/velocity.js"),_=n.n(g),b=n("./node_modules/vuescroll/dist/vuescroll-native.js"),y=n.n(b),x=n("./node_modules/hammerjs/hammer.js"),j=n.n(x),w=n("./node_modules/moment/moment.js"),k=n.n(w),M=n("./node_modules/vue-moment/dist/vue-moment.js"),S=n.n(M),L=n("./client/store/index.js"),T=n("./node_modules/js-cookie/src/js.cookie.js"),O=n.n(T),D=n("./client/modules/boot.js"),E=n("./client/modules/localization.js"),Y=n("./client/helpers/index.js");function A(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var i=Object.getOwnPropertySymbols(e);t&&(i=i.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,i)}return n}function P(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?A(Object(n),!0).forEach((function(t){C(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):A(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function C(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}window.WIKI=null,window.boot=D.a,window.Hammer=j.a,k.a.locale(siteConfig.lang),L.a.commit("user/REFRESH_AUTH");const I=window.location.protocol+"//"+window.location.host+"/graphql",R=("https:"===window.location.protocol?"wss:":"ws:")+"//"+window.location.host+"/graphql-subscriptions",N=c.ApolloLink.from([new u.ErrorLink(({graphQLErrors:e,networkError:t})=>{if(e){let t=!1;e.map(({message:e,locations:n,path:i})=>{"Forbidden"===e&&(t=!0),console.error("[GraphQL error]: Message: ".concat(e,", Location: ").concat(n,", Path: ").concat(i))}),L.a.commit("showNotification",{style:"red",message:t?"You are not authorized to access this resource.":"An unexpected error occured.",icon:"alert"})}t&&(console.error(t),L.a.commit("showNotification",{style:"red",message:"Network Error: ".concat(t.message),icon:"alert"}))}),new l.BatchHttpLink({includeExtensions:!0,uri:I,credentials:"include",fetch:function(e){function t(t,n){return e.apply(this,arguments)}return t.toString=function(){return e.toString()},t}(async(e,t)=>{let n=JSON.parse(t.body);n=n.map(e=>P(P({},e),{},{variables:JSON.parse(JSON.stringify(e.variables),(e,t)=>"__typename"===e?void 0:t)})),t.body=JSON.stringify(n);const i=O.a.get("jwt");i&&(t.headers.Authorization="Bearer ".concat(i));const r=await fetch(e,t),o=r.headers.get("new-jwt");return o&&O.a.set("jwt",o,{expires:365}),r})})]),H=new d.WebSocketLink({uri:R,options:{reconnect:!0,lazy:!0}});window.graphQL=new s.ApolloClient({link:Object(c.split)(({query:e})=>{const{kind:t,operation:n}=Object(m.getMainDefinition)(e);return"OperationDefinition"===t&&"subscription"===n},H,N),cache:new p.InMemoryCache,connectToDevTools:"development"===e.env.node_env}),t.default.config.productionTip=!1,t.default.use(r.a),t.default.use(h.a),t.default.use(a.a),t.default.use(E.a.VueI18Next),t.default.use(Y.a),t.default.use(v.a),t.default.use(S.a,{moment:k()}),t.default.use(y.a),t.default.prototype.Velocity=_.a,t.default.component("admin",()=>Promise.all([n.e("vendor"),n.e("admin")]).then(n.bind(null,"./client/components/admin.vue"))),t.default.component("editor",()=>Promise.all([n.e("vendor"),n.e("editor")]).then(n.bind(null,"./client/components/editor.vue"))),t.default.component("history",()=>Promise.all([n.e("vendor"),n.e("history")]).then(n.bind(null,"./client/components/history.vue"))),t.default.component("page-source",

**Comment by Smankusors** [comment] 2020-05-28 05:03
what browser do you use? Have you tried with another browser?

**Comment by choongwh** [comment] 2020-05-28 07:13
Thank you for reply. 
I have tried Chrome, Microsoft Edge, and tested on Windows 10 platform. 
I have also tried on Chrome and Mozilla Firefox on Linux platform. 
I have tested to edit the same page on my Android handphone. 
All give the same result. I am unable to update. 
Once click the button APPLY, the error message box will prompt out. 
Thank you. And hope you can look into it.

**Comment by Smankusors** [comment] 2020-05-28 14:41
actually can't reproduce this. Something missing on your reproduce steps.

**Comment by choongwh** [comment] 2020-05-28 15:54
It is not produce able from your system.
Maybe I upload a video and share.
Also, I can make a dummy login for you to test.

**Comment by choongwh** [comment] 2020-05-29 05:20
> actually can't reproduce this. Something missing on your reproduce steps.

How can I pass the login to you? So you can login to check? 
We have another setup, and it has no problem. 
I am here to understand it is installation problem, or any other problem?

**Comment by Smankusors** [comment] 2020-05-29 06:10
it's better wait for @NGPixel, I'm not the developer here

**Comment by choongwh** [comment] 2020-06-04 04:23
I have finally solved the problem. It is indeed a bug. 
Initially, the URL is https://www.something.com/
And it will give the "siteHost.splice is not a function" error. 

I go checked the code in the \wiki\server\graph\resolvers\site.js
Line  30:         
if (siteHost.endsWith('/')) {
        siteHost = siteHost.splice(0, -1)
}

I see there is a "/" at the end of the URL. 
Once I remove the "/" at end of the URL, everything works fine. 

Hope someone could look into this. Thank you.

**Comment by NGPixel** [comment] 2020-06-04 04:33
Fixed by c2a0773633cf389a880c7e9edf1b99f0f08238f4

**Closed by NGPixel** 2020-06-04 04:33 UTC
Labels: bug
