### ISSUE TITLE
logLevel in config.yml has no effect

### ISSUE THREAD

**Issue by mbotmcc** [Requarks/wiki#2497] opened 2020-09-24 14:53 UTC
Changing the **logLevel** from **info** to any of the other possible options (verbose, debug, silly etc) doesn't seem to have any effect. I get the same amount of logs and info with all options.

**Expected behavior**
Logging level should actually change

**Host Info (please complete the following information):**
 - docker image

image build using

```
FROM requarks/wiki:2.5.144

COPY --chown=node:node ./config/config.yml /wiki/config.yml
```

config.yml

```
port: 3000
bindIP: 0.0.0.0
db:
  type: $(DB_TYPE)
  host: '$(DB_HOST)'
  port: $(DB_PORT)
  user: '$(DB_USER)'
  pass: '$(DB_PASS)'
  db: $(DB_NAME)
  storage: $(DB_FILEPATH)
  ssl: $(DB_SSL)
ssl:
  enabled: false
  port: 3443
  provider: custom
  format: pem
  key: ...
  cert: ...

logLevel: debug
ha: $(HA_ACTIVE)
offline: false
```

**Comment by NGPixel** [comment] 2020-09-24 14:55
This is already being addressed in the next 3.0 update.

**Closed by NGPixel** 2020-09-24 14:55 UTC

**Comment by kmpm** [comment] 2020-11-09 11:17
@NGPixel could you please provide a commit or something so I could backport the fix to my current running version.
Would like to be able to troubbleshoot before 3.0.

**Comment by kevinremoue** [comment] 2021-04-16 01:25
@kmpm did you manage to get more logs ? 
I have the same issue and I can't wait for 3.0.

**Comment by NiceGuyIT** [comment] 2021-04-17 17:14
The problem isn't that `logLevel` has no effect. The problem is the application doesn't use debug logging. To verify this, search for `logger.debug` and there's only 4 instances, one of which logs attempts to do a password reset on a nonexistent account. For completeness, there's 0 `logger.silly` and `logger.verbose` instances.

```text
13:07:19 root@nb-01 /srv/d1/apps/wikijs/wikijs/server # rg logger.silly
13:07:25 root@nb-01 /srv/d1/apps/wikijs/wikijs/server # rg logger.debug
core/letsencrypt.js
44:            WIKI.logger.debug(`${ev}: ${JSON.stringify(msg)}`)

core/db.js
233:        WIKI.logger.debug(ev)

models/users.js
529:      WIKI.logger.debug(`Password reset attempt on nonexistant local account ${email}: [DISCARDED]`)
900:      WIKI.logger.debug(`Updating user ${userId} avatar data...`)
13:07:29 root@nb-01 /srv/d1/apps/wikijs/wikijs/server # rg logger.verbose
13:07:32 root@nb-01 /srv/d1/apps/wikijs/wikijs/server # 
```

After changing `logLevel: debug` and performing a password reset on `nonexistent@example.com`, a debug log message is output proving `logLevel` works.

```text
Apr 17 13:05:02 nb-01 node[15111]: 2021-04-17T17:05:02.678Z [MASTER] debug: Password reset attempt on nonexistant local account nonexistent@example.com: [DISCARDED]
```
