### ISSUE TITLE
When the search shows too many items, you cannot switch to the next page.

### ISSUE THREAD

**Issue by aaro-n** [Requarks/wiki#2276] opened 2020-08-08 23:24 UTC
I am using macbook pro 13 2018, with a display resolution of 2560 x 1600.
When searching, if there are too many entries, you cannot switch.
Phenomenon reproduced: https://docs.requarks.io/, search for the keyword "wiki", display 49 items, scroll up and down the browser, no change.
<img width="1346" alt="123" src="https://user-images.githubusercontent.com/45537680/89721498-db316200-da10-11ea-9009-de7bc7944431.png">

**Comment by Jhobean** [comment] 2020-08-09 03:06
This ?

https://github.com/Requarks/wiki/pull/2232

**Comment by aaro-n** [comment] 2020-08-09 03:23
Is the same problem

**Comment by Smankusors** [comment] 2020-08-09 04:17
Duplicate of #1672

**Closed** 2021-03-21 01:04 UTC
Labels: migrate
