### ISSUE TITLE
Cannot set page-specific write permissions

### ISSUE THREAD

**Issue by dakira** [Requarks/wiki#1425] opened 2020-01-31 13:09 UTC
I want some pages to be read-only and other pages to be writable. I set everything up as seen in the screenshot:

<img width="1103" alt="permissions" src="https://user-images.githubusercontent.com/576555/73541345-7af2af80-4432-11ea-9f5e-56f977426582.png">

- the first rule is to start by denying everything
- then I allow specific access to the homepage the users are directed to when logging in (read-only)
- I allow full access to the users readwrite-area
- I allow read-only to a special immutable area.

For reading this works as expected (e.g. other existing pages cannot be opened). For writing only the global content permissions seem to have any effect. If I disable global write, the user cannot write on any pages, no matter what the page-specific permissions are. If I enable global write, the user can write to all pages they have read permissions on, no matter what other page-specific permissions are set. Any help would be greatly appreciated. Not sure if this a bug or a lack of understanding on my part.

**Comment by dakira** [comment] 2020-02-03 14:17
@NGPixel maybe this is a bug? Am I "holding it wrong"? :)

**Comment by bobonthenet** [comment] 2020-02-06 20:44
I think I've identified the root cause of this issue but don't have time right now to do anything about it. In server/core/auth.js the function checkAccess takes in the user, the permission you are checking for and the page. On line 162 it checks for the appropriate global permission and if the user does not have it then false is returned, that is fine but then we don't look at the permission again. I believe each of the switch cases starting on line 176 also need to be checking for the permission. Not just if the path matches the rule type. So for example what I'm seeing is as follows:
1. We want to check for write permission, checkAccess is called.
2. The function identifies that the user has the global permission to write and moves on.
3. Now the path matching logic happens. The permission we care about is not considered here. A path match is found with no greater specificity denying it.
4. The function returns true.

I will submit a fix for this as soon as possible unless someone else is able to get to it first.

**Closed** 2020-02-07 19:26 UTC
Labels: help
