### ISSUE TITLE
default authentication via LDAP possible?

### ISSUE THREAD

**Issue by YuriMri** [Requarks/wiki#2295] opened 2020-08-14 06:47 UTC
**Question**
Hello,
we set up (great) Wiki.js in our organization and best user experience would be if default authentication would be using LDAP services. 
Meaning that during login you don't have to click on "Log In using LDAP/ Active Directory" button.
So far we did not find it in settings. 
Thanks

**Host Info (please complete the following information):**
OS:
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

Wiki.js version: 2.4.107 (also testing wiki has same issue version 2.3.81), Node.js = 14.6.0 (also testing wiki has same issue version 12.18.0)
Database engine: postgresql 12.3

**Comment by Smankusors** [comment] 2020-08-17 10:08
Duplicate of #1541

**Comment by SirGibihm** [comment] 2020-08-19 08:33
This issue will be solved with the upcoming release 2.5, which is the next update:  https://twitter.com/requarks/status/1278519017456746498

**Closed** 2020-08-23 17:05 UTC
Labels: help
