### ISSUE TITLE
Writing content - after a few Words i can't delete

### ISSUE THREAD

**Issue by Tutnich** [Requarks/wiki#2800] opened 2020-12-08 22:12 UTC
**Dggescribe the bug**
You create a page or update a Page with  a few words or Pictures, than i cant delete anymore.
You can mark a part and your can ad more words, but you cant delete anymore. I have this Prolbem at two Wiki JS Servers now.
I cant't be a Prolbem with my PC oder Server. I tried differnd Kind of PCs and look for Rules in Wiki JS but nothing helps.
All Users are affected. When i start i knew instance i dont have this Problem. I don't know why, but something went wrong and than you are get this Bug.

Sometimes you can use del, but not Enter. But this is rare.

**To Reproduce**
1. Create an New Page or Update a existing page (in visual editior)
2. Write a few Words or make a few changes
3. A bit later you notice that you cant delete anything.
4. There is no Errorcode. You can wirte more, but if you do, all changes will be lost.
5. Click Save an Leave the Page. You see all changes would be made until this Bug happens. Other is lost.
6. Update this Page again and start with Step two again. This goes endless.

**Expected behavior**
I want to write Content as usual and want to delete words, if i write something wrong.

**Screenshots**
there is noting to see. Its lite this is a seeentence.
Now you press "del", but nothing happens.

**Host Info:**
 - OS: Debian 10
 - Wiki.js: 2.5.170
 - Database is Postgre SQL

The other Server is:
- OS: Windows Server 2019
 - Wiki.js : 2.5.170
 - Database is MySQL

**Additional context**
Sry for my bad English. I try my best. Thanks for this good software and any Help. Google can't help me.

**Comment by NGPixel** [comment] 2020-12-08 23:38
Are you using Firefox?

**Comment by Tutnich** [comment] 2020-12-09 15:52
Yes, i do. One of us is using Wikijs with Chrome without trouble. Is there any Problem with Firefox?

**Comment by NGPixel** [comment] 2020-12-09 15:57
Duplicate of #2758

**Closed by NGPixel** 2020-12-09 15:57 UTC
