### ISSUE TITLE
Changing pages on wiki pages flashes gray on change

### ISSUE THREAD

**Issue by doits** [Requarks/wiki#932] opened 2019-07-19 11:06 UTC
I know it is still an early beta and this is just an annoyance, but still: When switching pages there is always a flash of dark gray while the new page is loading:

![Jul-19-2019 13-02-50](https://user-images.githubusercontent.com/148003/61530856-8eee3b00-aa25-11e9-9344-57cd90f9e802.gif)

Sometimes it just flashes for some milliseconds, sometimes it takes a little bit (like in the video above).

It just irritates me while browsing the wiki, maybe there is an easy fix for it.

**Comment by NGPixel** [comment] 2019-07-20 02:48
Duplicate of #817

**Closed by NGPixel** 2019-07-20 02:48 UTC
