### ISSUE TITLE
save.saved appearing on save button

### ISSUE THREAD

**Issue by depict1** [Requarks/wiki#1650] opened 2020-03-31 14:03 UTC
**Describe the bug**
The save button is broken.

**Expected behavior**
It should say Saved

**Screenshots**
![image](https://user-images.githubusercontent.com/57202889/78035202-62b5e880-732e-11ea-9cd6-abf2e7432135.png)

**Host Info (please complete the following information):**
2.2.50

**Additional context**
I cleared my cache. Still appears on different computers and browsers.

**Comment by NGPixel** [comment] 2020-04-01 00:31
Closing as it's caused by #1649

**Closed by NGPixel** 2020-04-01 00:31 UTC
