### ISSUE TITLE
ul>ul padding error

### ISSUE THREAD

**Issue by fanlix** [Requarks/wiki#1188] opened 2019-11-06 08:01 UTC
**Describe the bug**
markdown mode
for nesting ul / ol, the padding is not right.

**To Reproduce**
in markdown mode, create a page like this:
```
- line one
  - line one.1
  - line one.2
- line two
  * 2.1
    * 2.1.1
  * 2.2
```

**Expected behavior**
padding and align all error

**Screenshots**

**Host Info (please complete the following information):**
 - OS: docker = requarks/wiki:beta-arm   version:7364b3ae47eb
 - Wiki.js version: 2.0.0.rc.17
 - Database engine: sqlite

**Additional context**

**Comment by fanlix** [comment] 2019-11-06 08:03
![wikijs_bug](https://user-images.githubusercontent.com/987637/68279726-01575980-00af-11ea-9a8b-d7206c01fb03.PNG)

**Comment by SharkProgramming** [comment] 2019-11-06 08:08
in addition , i have the same issue 
![issue4](https://user-images.githubusercontent.com/33226400/68280004-f1228880-0074-11ea-9624-60b37ee5e8c9.png)


**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04.3
 - Wiki.js version: 2.0.0-rc.17
 - Database engine: MariaDB 10.3.18

**Comment by NGPixel** [comment] 2019-11-06 08:51
Duplicate of #1114

**Closed by NGPixel** 2019-11-06 08:51 UTC
