### ISSUE TITLE
Unable to assign a user to administrators group

### ISSUE THREAD

**Issue by fosshostorg** [Requarks/wiki#2436] opened 2020-09-13 13:12 UTC
Hi. 

I get the following error when I attempt to add a user to the administrators group.  This wasn't happening prior to the 2.5.132 upgrade.  The user I am logged in with is the full admin account, so has full admin permissions, so that doesn't make sense.

GraphQL error: You are not authorized to assign a user to this elevated group.

I thought to get around this I would set up a new group called admin and assign as many permissions as possible to try and replicate administrators group.  It is telling me the following error when I try to assign admin permissions to it: 

You are not authorized to assign a user to this elevated group.  

I can assign some basic permissions like to create and edit a page, but when I enable these, and then log in with the respective user, the icon and option to edit page is not there.  I have tried from various browsers and logged out and back in.

Everything was going so well, these issues have only started after the last two updates over the last week.

Thanks

**Comment by fosshostorg** [comment] 2020-09-13 13:12
System Info
System Info
Information about your system
Wiki.js
Current Version
2.5.132
Latest Version
2.5.132
Published 4 days ago
Host Information
Operating System
Docker Container (Linux)
Hostname
wiki
CPU Cores
1
Total RAM
985.19 MB
Working Directory
/wiki
Configuration File
/wiki/config.yml
Node.js
14.10.0
PostgreSQL
11.8
db

**Comment by Igorgro** [comment] 2020-09-13 14:11
Duplicate of https://github.com/Requarks/wiki/issues/2424

**Comment by fosshostorg** [comment] 2020-09-13 15:21
Sorry this isn’t explicitly clear. What do I need to do to fix this?

Thank you.

On 13 Sep 2020, at 15:11, Igor Mahov <notifications@github.com> wrote:

﻿

Duplicate of #2424<https://github.com/Requarks/wiki/issues/2424>

**Comment by Igorgro** [comment] 2020-09-13 15:21
You should upgrade to latest version

**Comment by fosshostorg** [comment] 2020-09-13 15:50
I already have and the issue is still there..

On 13 Sep 2020, at 16:22, Igor Mahov <notifications@github.com> wrote:

﻿

You should upgrade to latest version

**Comment by NGPixel** [comment] 2020-09-13 17:42
You're not on latest version. You listed 2.5.132 while the latest is 2.5.136. This is fixed in 136.

**Closed by NGPixel** 2020-09-13 17:42 UTC
Labels: help

**Comment by fosshostorg** [comment] 2020-09-13 19:14
I’m installing the latest versions that are pushed via the web administration console. It is not giving me an option to install a newer version :)

On 13 Sep 2020, at 18:42, Nicolas Giard <notifications@github.com> wrote:

﻿

You're not on latest version. You listed 2.5.132 while the latest is 2.5.136. This is fixed in 136.

**Comment by NGPixel** [comment] 2020-09-13 19:34
You need to either wait 24h for your installation to check for new updates or restart the container to force one.
