### ISSUE TITLE
<figcaption> not rendered

### ISSUE THREAD

**Issue by carloposo** [Requarks/wiki#1594] opened 2020-03-18 14:06 UTC
### Actual behavior
All picture captions are rendered as `<figcaption>My caption text</figcaption>`

![Screenshot 2020-03-18 at 15 07 31](https://user-images.githubusercontent.com/1691849/76969156-4b3c3000-692a-11ea-9273-00a9089e9c81.png)

### Expected behavior
<figcaption> tag should be rendered with the correct style

### Steps to reproduce the behavior
Try to add a caption.

**Comment by NGPixel** [comment] 2020-03-19 02:35
Duplicate of #1587

**Closed by NGPixel** 2020-03-19 02:35 UTC
