### ISSUE TITLE
Bug: `amp;` in LaTex

### ISSUE THREAD

**Issue by time-river** [Requarks/wiki#649] opened 2018-10-05 08:12 UTC
### Actual behavior
wikijs version： 1.0.102 Release

I write a LaTex formulation in wiki, Here:
```
$$
\max_{\boldsymbol{\alpha}} = \sum_{i=1}^{m}\alpha_i - \frac{1}{2} \sum_{i=1}^{m}\sum_{j=1}^{m}\lambda_i \lambda_j \boldsymbol{x}_i^T \boldsymbol{x}_j \\
\begin{align}
& s.t. & \quad \sum_{i=1}^{m}\alpha_i y_i = 0, \\
& & \alpha_i \geq 0, \ i = 1, 2, 3, ..., m
\end{align}
$$
```
It's shows:

![](https://s1.ax1x.com/2018/10/05/i8dE0U.png)

### Expected behavior

not exist `amp;`

### Steps to reproduce the behavior

write some LaTex formulation .

**Comment by NGPixel** [comment] 2018-10-11 02:31
Duplicate of #525

**Closed by NGPixel** 2018-10-11 02:31 UTC
