### ISSUE TITLE
GIT: incomplete handling of git changes (move, rename, delete)

### ISSUE THREAD

**Issue by akaRem** [Requarks/wiki#1440] opened 2020-02-05 20:40 UTC
**Describe the bug**
If file is moved/renamed in git repo, it produces duplicated article in new path
If file is removed/deleted, it doesn't remove related page in db

**To Reproduce**
1. enable and configure git with bi-dir sync
2. commit a file and push
3. wait for sync
4. move/rename the file, commit and push
5. on wiki you will have 2 pages

**Expected behavior**
If file is renamed or moved in git repo, page should change it's path in wiki engine w/o creation of new page
if file is deleted from git, related page should be removed from wiki engine

**Screenshots**

**Host Info (please complete the following information):**
 - OS: docker/linux
 - Wiki.js version: 2.0.12
 - Database engine: postgres 9.7

**Additional context**

**Comment by Jeewes** [comment] 2020-06-25 17:33
I bumped into the same/similar problem. My steps to reproduce:

1. Enable and configure git with bidirectional sync
1. Move file and  commit (e.g. with `git mv`)
1. Force sync

Didn't notice two pages, but I noticed that the page path did not change. Trying to move the page via Wiki.js UI failed with an error message, but after that the page can be found from the new path and not from the old path.

This might be tricky, but I agree with @akaRem about the **expected behavior**. This would make mass editing of the page structure much easier.

**Used version:** 2.4.105

**Comment by derf** [comment] 2020-07-11 11:48
Same here. My workaround is to disable rename detection altogether and handling a rename as delete + add instead. This is probably not an elegant solution, but far better than a Wiki which breaks on renames. I'm attaching the patch for reference.

```

diff --git a/server/modules/storage/git/storage.js b/server/modules/storage/git/storage.js
index 7f5c1e66..4b93aa87 100644
--- a/server/modules/storage/git/storage.js
+++ b/server/modules/storage/git/storage.js
@@ -138,7 +138,7 @@ module.exports = {
     if (_.includes(['sync', 'pull'], this.mode)) {
       const latestCommitLog = _.get(await this.git.log(['-n', '1', this.config.branch]), 'latest', {})
 
-      const diff = await this.git.diffSummary(['-M', currentCommitLog.hash, latestCommitLog.hash])
+      const diff = await this.git.diffSummary(['--no-renames', currentCommitLog.hash, latestCommitLog.hash])
       if (_.get(diff, 'files', []).length > 0) {
         let filesToProcess = []
         for (const f of diff.files) {
```

**Comment by NGPixel** [comment] 2020-11-08 20:09
Duplicate of #1358

**Closed by NGPixel** 2020-11-08 20:09 UTC
