### ISSUE TITLE
Ability to delete post/page from within wiki.js

### ISSUE THREAD

**Issue by cisspking** [Requarks/wiki#231] opened 2017-09-06 20:39 UTC
### Actual behavior
Unable to delete page/post form wiki ui.

**Comment by NGPixel** [comment] 2017-09-08 01:51
This is planned for 2.0

**Comment by KovganIV** [comment] 2017-09-30 17:54
Please, release v2.0 faster :)

**Comment by NGPixel** [comment] 2017-10-01 03:55
Closing as duplicate of #167

**Closed by NGPixel** 2017-10-01 03:55 UTC
Labels: deferred
