### ISSUE TITLE
Breadcrumb navigation issues with locale and other misc issue

### ISSUE THREAD

**Issue by damo78** [Requarks/wiki#1093] opened 2019-10-10 19:03 UTC
**Describe the bug**
The breadcrumb navigation does not take into account the locale in the URL so results in a 404 when clicking the breadcrumb navigation.  There is also strange behaviour when selecting the current page breadcrumb item.

Note, that Pages currently on allow me to have an `en` which becomes prepended in the URL

**To Reproduce (Locale)**
1. Create a menu nav-link that results in a URL `my-domain/nav-item-page`
2. Create a Page with the target for the above nav-link, e.g. `nav-item-page`
3. Create another Page, e.g. `breadcrumb-page`, with the URL to create the breadcrumb as `/nav-item-page/breadcrumb-page`
4. Create another Page, e.g. `breadcrumb-subpage`, with the URL to create the breadcrumb as `/nav-item-page/breadcrumb-page/breadcrumb-subpage`
5. Navigate to `my-domain/nav-item-page/breadcrumb-page/breadcrumb-subpage`
6. Now select any of the previous breadcrumbs items
7. This will cause an issue because the URL has changed to `my-domain/en/nav-item-page/breadcrumb-page/breadcrumb-subpage`

**To Reproduce (Misc)**
Starting from step 5 above, whilst on `my-domain/nav-item-page/breadcrumb-page/breadcrumb-subpage`
1. Select the breadcrumb items for `breadcrumb-subpage`
2. The URL will change to something like this: `my-domain/nav-item-page/nav-item-page/breadcrumb-page/nav-item-page/nav-item-page/breadcrumb-subpage`

**Expected behavior**
The breadcrumb item should navigate to the correct page

**Screenshots**
n/a

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04, Docker
 - Wiki.js version: 2.0.0-beta.303
 - Database engine: postgres 9.7

**Additional context**
N/A

**Comment by jimmybrancaccio** [comment] 2019-10-23 16:50
I can confirm it looks like this is happening in RC1 as well.

**Comment by NGPixel** [comment] 2019-10-27 21:40
Duplicate of #930, fixed by c83eb255141e4cce12532081ea7b26821902f318

**Closed by NGPixel** 2019-10-27 21:40 UTC
Labels: under review
