### ISSUE TITLE
Visual Editor Not Working in Firefox in wiki.js version 2.5.170

### ISSUE THREAD

**Issue by Weitspringer** [Requarks/wiki#2758] opened 2020-11-25 16:57 UTC
**Describe the bug**
The visual editor is not working when modifying pages at random times.

**To Reproduce**
1. Create a page with visual editor and type several words in the content field
2. Save page
3. Modify the same page
4. Play around. Type random characters and try to delete them with backspace. Navigate in the middle of some word with the mouse, type and delete. ...
5. Sometimes you can not delete the chars you wrote for no reason
6. At this point, nothing works anymore
7. If you can not reproduce, save the page and try again to modify it.

_Or see below in the comments_

**Expected behavior**
Deletion of characters does not work anymore, neither marking words or erase markings. The whole editor won't behave as expected. It will just "freeze".

**Host Info (please complete the following information):**
 - OS: Docker (Linux)
 - Wiki.js version: 2.5.170
 - Database engine: postgres 10.11

**Comment by Openanonwriter** [comment] 2020-11-25 17:11
# There are multiple reports of this, I do not know how to combined them. But here are 3 more. 
You are not alone. 
https://github.com/Requarks/wiki/issues/2753#issuecomment-733301986

**Comment by Weitspringer** [comment] 2020-11-25 19:55
Error in line 7 of _assets/editor-ckeditor.js

![Inkedckeditor_LI](https://user-images.githubusercontent.com/35311367/100275575-7585c900-2f60-11eb-9728-b629cc7ce459.jpg)

**Comment by DGEllis** [comment] 2020-11-29 12:54
I have the same issue. Shift-reload will clear the problems, but that's sub-optimal. One backspace is all it takes for it to tail. This didn't start until I exceeded 50 pages in my Wiki.js.

**Comment by Weitspringer** [comment] 2020-11-29 20:53
> 
> 
> I have the same issue. Shift-reload will clear the problems, but that's sub-optimal. One backspace is all it takes for it to tail. This didn't start until I exceeded 50 pages in my Wiki.js.
 
Our wiki did not even exceed 5 pages

**Comment by NGPixel** [comment] 2020-11-29 21:57
The amount of pages in your wiki is totally unrelated to this issue.

Which browser are you using? Have you tried other browsers?

**Comment by DGEllis** [comment] 2020-11-30 12:08
I primarily use Firefox. I will test and report using the following browses:
Firefox Developer
Latest M$ Edge
Opera
Chrome

My primary workstation is a Mac.

**Comment by DGEllis** [comment] 2020-12-01 18:07
Thinking it would be easy to confirm a Firefox error, I tried with Firefox Developer Edition. The problem did NOT occur. I decided to look at plugins/extensions as I keep the developer edition without plugins.

The only extension I have is Dashlane. The only plugins are the two stock plugins.

**Comment by DGEllis** [comment] 2020-12-01 18:09
Next I tried Chrome. I was able to use backspace without the problem occurring. Dashlane IS installed in Chrome.

**Comment by Weitspringer** [comment] 2020-12-02 17:38
> 
> 
> The amount of pages in your wiki is totally unrelated to this issue.
> 
> Which browser are you using? Have you tried other browsers?

I use Firefox and haven't tried other browsers yet. Another user reported the same issue to me, also using Firefox.

**Comment by stusherwin** [comment] 2020-12-02 22:30
I'm also having the same issue in Firefox - the visual editor is basically unusable.

```
Uncaught CKEditorError: a is undefined editor-ckeditor.js:7:21247

```
Wiki.js 2.5.170
Firefox 83.0 (64-bit)
Windows 8.1

**Comment by DGEllis** [comment] 2020-12-03 14:41
I can confirm that it's the latest release of Firefox. This morning my developer edition updated to current and wiki.js no longer works with the developer edition.

M$ Edge seems to work, as does Chrome. I just now confirmed that the problem does not occur under Opera.

My system is Mac Mini, Bug Sur.

**Comment by betepok13** [comment] 2020-12-04 09:28
Firefox v.83.0 64bit.
I print any text and press periodically backspace/delete. Everything is ok right away, but then an error occurs and it is impossible to delete the text. Suddenly, it will help in finding the bug. This is what it writes in the browser console:

![изображение](https://user-images.githubusercontent.com/40733196/101146160-bac68c80-362b-11eb-987e-ebfbde864dae.png)

This happened right after the upgrade to version Wiki.js 2.5.170

**Comment by nook24** [comment] 2020-12-07 12:44
I have the same issue with **Firefox 83.0** on macOS 10.15.7.
- Keys not working: Backspace and return (maybe others?)
- I also can not insert images.

It looks like the issue occurs as soon as you press backspace for the first time.

But it works with Google Chrome 86.0.4240.198

**Comment by shaqman** [comment] 2021-01-06 06:28
I have the same issue on Firefox 84.0 on Linux 20.04.
It doesn't really seems to be related to firefox version it seems.

**Comment by wdko** [comment] 2021-01-08 07:56
Same problem here using Firefox 84.0.2 on windows 10.  
When i create a new page, write a line of text and press backspace i get the following.
When i save this page, part of the text is gone.

`Uncaught CKEditorError: a is undefined
    js http://localhost:8107/_assets/js/app.js?1603683027:350
    getMinimalFlatRanges http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    execute http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    _runPendingChanges http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    enqueueChange http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    execute http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    decorate http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    fire http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    t http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    execute http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    execute http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    init http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    fire http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    n http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    Au http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    fire http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    fire http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    onDomEvent http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    observe http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    fire http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    i http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
editor-ckeditor.js:7:21247
    n http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    rethrowUnexpectedError http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    enqueueChange http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    execute http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    decorate http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    fire http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    t http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    execute http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    execute http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    init http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    fire http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    n http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    Au http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    fire http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    fire http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    onDomEvent http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    observe http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    fire http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    i http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
Uncaught CKEditorError: Index or size is negative or greater than the allowed amount
    viewRangeToDom http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    scrollToTheSelection http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    init http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    fire http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    zd http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    fire http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    fire http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    onDomEvent http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    observe http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    fire http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    i http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
editor-ckeditor.js:7:21247
    n http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    rethrowUnexpectedError http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    fire http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    zd http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    fire http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    fire http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    onDomEvent http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    observe http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    fire http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    i http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
Uncaught CKEditorError: Index or size is negative or greater than the allowed amount
    viewRangeToDom http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    scrollToTheSelection http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    init http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    fire http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    n http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    Au http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    fire http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    fire http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    onDomEvent http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    observe http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    fire http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    i http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
editor-ckeditor.js:7:21247
    n http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    rethrowUnexpectedError http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    fire http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    n http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    Au http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    fire http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    fire http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    onDomEvent http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    observe http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    fire http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7
    i http://127.0.0.1:8107/_assets/js/editor-ckeditor.js?1603683027:7`

**Comment by cvhainb** [comment] 2021-01-13 06:18
I have the same issue.

**Comment by Jordi-m** [comment] 2021-01-13 10:47
I've setup Wiki.JS yesterday (using the latest Docker image) and for almost every edit in the CKEditor, I'm getting a similair error in the Firefox dev console:

    `Uncaught CKEditorError: a is undefined`

This happens in 60-80% of the cases when I copy/paste content from a Google Document file into the editor. After the error, the editor 'freezes'. Sometimes the editor doesn't freeze, but if you save the page, the changes are not stored. It's hard to make modifications afterwards, because some parts of the page seem to be 'broken': I cant make modifications on those parts, while other parts (trial and error) can be extended/modified.

I expected that it might be caused by messy HTML due to the copy/paste, but unfortunately when I pick the WYSIWYG editor, I'm unable to clean up the HTML manually via the web interface. (a 'view source code' option for the WYSIWYG editor would be nice, but I saw that has already requested and looked into a while ago).

Full error:

```
Uncaught CKEditorError: a is undefined
    js https://my-wiki-site.nl/_assets/js/app.js?1603683027:350
    _previous https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    next https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    getNearestSelectionRange https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    getNearestSelectionRange https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    _fixGraveyardSelection https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    Dr https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    fire https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    t https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    qs https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    remove https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    _checkAndSplitToAllowedPosition https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    _handleNode https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    handleNodes https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    insertContent https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    _runPendingChanges https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    change https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    insertContent https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    insertContent https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    decorate https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    fire https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    t https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    init https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    fire https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    init https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    fire https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    i https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    fire https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    fire https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    onDomEvent https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    observe https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    fire https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    i https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
editor-ckeditor.js:7:21247
    n https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    rethrowUnexpectedError https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    fire https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    t https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    qs https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    remove https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    _checkAndSplitToAllowedPosition https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    _handleNode https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    handleNodes https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    insertContent https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    _runPendingChanges https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    change https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    insertContent https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    insertContent https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    decorate https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    fire https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    t https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    init https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    fire https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    init https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    fire https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    i https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    fire https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    fire https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    onDomEvent https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    observe https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    fire https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
    i https://my-wiki-site.nl/_assets/js/editor-ckeditor.js?1603683027:7
```

**Comment by warkadiuszz** [comment] 2021-01-15 18:09
Exactly the same problem here.

Firefox 84.0.2 64-bit, Wiki.js 2.5.170, getting `Uncaught CKEditorError: a is undefined` on fresh installation.

**Comment by temrix** [comment] 2021-01-17 15:28
@NGPixel Hello, I am working with a small team on a game and we are reliant on Wiki.js for our project as many of our members work with the Visual Editor.

I have tried using the `DecoupledEditor` from `@ckeditor/ckeditor5-build-decoupled-document` instead of the now used fork DecoupledEditor from `@requarks/ckeditor5` which already is a pretty old version of the original.

Visual editor works when I replace it with the newer version from `@ckeditor/ckeditor5-build-decoupled-document`.

**Comment by khedrub** [comment] 2021-01-21 23:03
For me this fix does not worked. 
Cloned the repo, pulled the fix, build the app and ran it. The visual editor is still broken. 
I verified that it actually useses the "DecoupledEditor".

I really want to start using WikiJS in my company, already invested plenty of time in it, but this issue is open since November and it is kind of a dealbreaker not to be able to use firefox with the visual editor.

**Comment by temrix** [comment] 2021-01-22 10:35
@khedrub ~~Have you checked out the right branch using `git checkout fix/visual-editor-update`?~~ You're right, still does not work. The version should be updated nonetheless, though. Related to https://github.com/ckeditor/ckeditor5/issues/8740 and they need steps to reproduce if it's a bug on their behalf.

**Comment by Weitspringer** [comment] 2021-01-29 11:51
> I really want to start using WikiJS in my company, already invested plenty of time in it, but this issue is open since November and it is kind of a dealbreaker not to be able to use firefox with the visual editor.

Same here. I appreciate this project but we really need the visual editor to work with Firefox.

**Comment by temrix** [comment] 2021-02-13 14:12
I am unable to trigger this bug in Firefox v85.0.2 so this seems to have been fixed in Firefox.

**Comment by NGPixel** [comment] 2021-03-21 01:27
Closing as this is no longer reproducible in latest Firefox.

**Closed by NGPixel** 2021-03-21 01:27 UTC
Labels: bug, under review
