### ISSUE TITLE
Black Screen when i click another menu.

### ISSUE THREAD

**Issue by snowdream** [Requarks/wiki#817] opened 2019-04-26 02:06 UTC
### Actual behavior
Black Screen

### Expected behavior
No Black Screen

### Steps to reproduce the behavior
1. open the demo site with chrome on macos : https://docs-beta.requarks.io/
2. click the menu: requirements
3. then click another menu: Installation
4. you will see a black screen .

[![](http://img.youtube.com/vi/Zdah-RBnVDQ/0.jpg)](http://www.youtube.com/watch?v=Zdah-RBnVDQ "AwesomeScreenshot 2019 04 26T02 00 02 038Z")

**Comment by NGPixel** [comment] 2019-07-21 02:46
Fixed by 006fd59e2a1a6ce6b73dd0bda501243b4342788f

**Closed by NGPixel** 2019-07-21 02:46 UTC
Labels: enhancement

**Comment by doits** [comment] 2019-07-24 14:00
@NGPixel thanks for the quick fix! It does not flash *gray* anymore, though it flashes *white* now ... Looks like the root cause for flashing is still there.

Should this issue be repoened or do you want to have it as a new issue?
