### ISSUE TITLE
Having an Avatar Picture Field Mapping value configured in LDAP settings breaks LDAP authentication.

### ISSUE THREAD

**Issue by bagovino** [Requarks/wiki#1029] opened 2019-09-11 16:15 UTC
Version: Wiki.js 2.0.0-beta.275 using Docker

### Actual behavior

Having an Avatar Picture Field Mapping value configured in LDAP settings breaks LDAP authentication.

### Expected behavior

Having an Avatar Picture Field Mapping configured in LDAP settings should not break LDAP authentication.

### Steps to reproduce the behavior

Configure the LDAP authentication in strategy with appropriate values. In our case the Avatar Picture Field Mapping value should be "thumbnailPhoto". Create a new user using the LDAP strategy. Attempt to login as that user and we get the error as shown in the screenshot. Removing the value in Avatar Picture Field Mapping works around the error and allows the user to log in.

I'm pretty sure we store the image file directly in thumbnailPhoto attribute... I'm not sure if that might be the issue here if some other value is expected.

<img width="717" alt="Screen Shot 2019-09-11 at 12 05 24 PM" src="https://user-images.githubusercontent.com/940804/64715056-c3aec980-d48d-11e9-9663-751c476d11f7.png">

**Comment by NGPixel** [comment] 2019-09-13 20:21
Duplicate of #849 . Set the avatar field to something else for now, binary blob pictures are breaking the user update process.

**Closed by NGPixel** 2019-09-13 20:21 UTC
