### ISSUE TITLE
Fetching locale pt-br from Graph endpoint: [ FAILED ] using MSSql database

### ISSUE THREAD

**Issue by hugomarshall** [Requarks/wiki#929] opened 2019-07-18 02:18 UTC
2019-07-18T02:13:46.356Z [MASTER] info: Fetching locale pt-br from Graph endpoint...
2019-07-18T02:13:47.057Z [MASTER] error: Fetching locale pt-br from Graph endpoint: [ FAILED ]
2019-07-18T02:13:47.058Z [MASTER] error: insert into [locales] ([availability], [code], [createdAt], [isRTL], [name], [nativeName], [strings], [updatedAt]) output inserted.[code] values (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7) - String or binary data would be truncated.
2019-07-18T02:14:02.195Z [MASTER] info: Fetching locale es from Graph endpoint...
2019-07-18T02:14:02.963Z [MASTER] info: Fetching locale es from Graph endpoint: [ COMPLETED ]
2019-07-18T02:14:18.222Z [MASTER] info: Fetching locale pt-br from Graph endpoint...
2019-07-18T02:14:18.489Z [MASTER] error: Fetching locale pt-br from Graph endpoint: [ FAILED ]
2019-07-18T02:14:18.490Z [MASTER] error: insert into [locales] ([availability], [code], [createdAt], [isRTL], [name], [nativeName], [strings], [updatedAt]) output inserted.[code] values (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7) - String or binary data would be truncated.

**Comment by NGPixel** [comment] 2019-07-18 03:21
Duplicate of #926

**Closed by NGPixel** 2019-07-18 03:21 UTC
Labels: duplicate
