### ISSUE TITLE
The login page always redirects to home, losing the original path/URL to a given page

### ISSUE THREAD

**Issue by nio101** [Requarks/wiki#229] opened 2017-09-05 14:07 UTC
If a given local user has a read permission on a given /test page, but not on the main page, when he tries to access the http://wiki/test URL, he has to login, but after that he is always redirected to the home page, and thus gets an error message (due to lack of read permission), instead of being sent to the /test page he asked for.

**Comment by NGPixel** [comment] 2017-09-06 00:08
Duplicate of #141 

Will be fixed in 2.0

**Closed by NGPixel** 2017-09-06 00:08 UTC
