### ISSUE TITLE
Can't click on table of content (2.0.0-rc.1)

### ISSUE THREAD

**Issue by Jerome38** [Requarks/wiki#1142] opened 2019-10-24 20:33 UTC
**Describe the bug**
When i click on section on the table of content, it doesn't scroll.
I have this javascript issue on the console : 

```
app.1870d78543a738b1b5e9.js:58 TypeError: Target must be a Number/Selector/HTMLElement/VueComponent, received undefined instead.
    at k (app.1870d78543a738b1b5e9.js:58)
    at Object.O (app.1870d78543a738b1b5e9.js:58)
    at click (theme-page.e517cdd6e27827027d34.js:2)
    at qt (app.1870d78543a738b1b5e9.js:58)
    at a.n (app.1870d78543a738b1b5e9.js:58)
    at qt (app.1870d78543a738b1b5e9.js:58)
    at a.t.$emit (app.1870d78543a738b1b5e9.js:58)
    at a.click (app.1870d78543a738b1b5e9.js:58)
    at qt (app.1870d78543a738b1b5e9.js:58)
    at HTMLDivElement.n (app.1870d78543a738b1b5e9.js:58)
```

**To Reproduce**
1. Create page with visual editor
2. Create multitle title
3. Save
4. Try to scroll with the table of content

**Expected behavior**
Page should scroll

**Comment by NGPixel** [comment] 2019-10-27 21:54
Duplicate of #1127

**Closed by NGPixel** 2019-10-27 21:54 UTC
