### ISSUE TITLE
search results are not scrollable

### ISSUE THREAD

**Issue by akaRem** [Requarks/wiki#1443] opened 2020-02-05 21:26 UTC
**Describe the bug**

**To Reproduce**
1. goto https://docs.requarks.io
2. Click on search, type 'file'
3. there are ±24 search results, only ± 10 is available

**Expected behavior**
to be able to inspect all results.

**Comment by akaRem** [comment] 2020-02-05 21:27
(and close button is not reachable)

**Comment by NGPixel** [comment] 2020-02-06 04:08
Duplicate of #942

**Closed by NGPixel** 2020-02-06 04:08 UTC
