### ISSUE TITLE
left bar function not available

### ISSUE THREAD

**Issue by kyhuynhduc** [Requarks/wiki#2574] opened 2020-10-13 08:45 UTC
**Question**
open new markdown page, left bar function not available as picture below, plese help.
<img width="1440" alt="Ảnh chụp Màn hình 2020-10-13 lúc 15 40 50" src="https://user-images.githubusercontent.com/36893030/95837899-5abe1300-0d6b-11eb-9bd5-787f978c6b08.png">

**Comment by Smankusors** [comment] 2020-10-13 09:41
Duplicate of #1504

**Closed** 2021-03-21 00:54 UTC
Labels: help
