### ISSUE TITLE
Code Blocks: long lines get broken in multiple lines

### ISSUE THREAD

**Issue by Znuff** [Requarks/wiki#1148] opened 2019-10-26 15:12 UTC
**Describe the bug**

Long code lines that normally SHOULD wrap properly get broken in multiple lines upon page view.

For example, a line like:

https://i.imgur.com/syig4Vb.png

Will end up being broken in the page output like:

https://i.imgur.com/Veki78o.png

Curiously, in the preview area it actually works properly:

https://i.imgur.com/TWtwABM.png

(as a side note, when pasting very long lines in code blocks in the markdown editor, the preview pane gets completely obliterated, I had to apply some CSS manually to be able to take the screenshot above)

**To Reproduce**
1. Create a new page, use Markdown
2. Insert a code block, paste very long lines (like public ssh keys)
3. Save page
4. Rendered page will break down the SSH key in 2 or 3 lines, when copying it and pasting it to anything else, it will obviously be broken

**Expected behavior**
Lines should wrap properly like in the preview 

**Screenshots**
Screenshots above in description

**Host Info (please complete the following information):**
 - OS: Ubuntu 17.10
 - Wiki.js version: 2.0.0-rc1
 - Database engine: sqlite

**Additional context**
Let me know if you would rather I make a separate bug for the preview pane.

**Comment by NGPixel** [comment] 2019-10-26 16:14
Duplicate of #1079

**Closed by NGPixel** 2019-10-26 16:14 UTC
