### ISSUE TITLE
Unable to delete stored images

### ISSUE THREAD

**Issue by failover88** [Requarks/wiki#1674] opened 2020-04-05 17:53 UTC
**Describe the bug**
When I try to delete stored images that are not in use, I am unable to achieve it, I got an error in every delete I try to do.

**To Reproduce**
1. Go to any page created already
2. Click to add an image, and try to delete one of those
3. And got the following erro popup: 

Variable "$id" of non-null type "Int!" must not be null.

**Screenshots**

http://prntscr.com/rtk01u

**Host Info (please complete the following information):**
WikiJS: 2.2.51
OS: Debian 9.12 x64
Node.js: 10.19.0
Database engine: PostgreSQL 9.6.17

**Comment by failover88** [comment] 2020-04-05 17:56
I discover that It must be selected first the image, before choose the ... on target image.

Not an intuitive way to achieve it, I think.

Thanks anyway!

**Comment by Smankusors** [comment] 2020-04-05 19:15
duplicate of #1518 and #1493 

well you can close this if you want...

**Closed** 2020-04-05 23:33 UTC
