### ISSUE TITLE
Discord oAuth: Two different servers collide

### ISSUE THREAD

**Issue by tionis** [Requarks/wiki#3187] opened 2021-03-07 13:20 UTC
**Describe the bug**
When two different servers are set as different authentication providers (or to be more exact two discord oAuth logins with different servers assigned) they collide. Users will always login as the last added discord user or cannot login at all.

**To Reproduce**
Add two discord oAuth Logins via the same client id and add different server ids

**Expected behavior**
The user should be logged in as the user account at the specific server

**Host Info:**
 - OS: Docker
 - Wiki.js version: 2.5.170
 - Database engine: postgres 11.10

**Comment by NGPixel** [comment] 2021-03-07 21:00
Duplicate of #2554

**Closed by NGPixel** 2021-03-07 21:00 UTC
