### ISSUE TITLE
creation of inaccessible pages

### ISSUE THREAD

**Issue by bitworm** [Requarks/wiki#96] opened 2017-05-03 17:15 UTC
### Actual behavior
saving an erring .md results in a limbo page that is inaccessible.  It can't be created because it "already exists", but can't be accessed because it "doesn't exist yet"

### Expected behavior
either allow edit of erring page, or don't create it.

### Steps to reproduce the behavior
1) "+ create" a new page, edit with error (e.g. empty header), then "save document" 
2) get error box "Something went wrong, something went wrong"
3) forced to "discard changes"
...
4) "+ create" same page, results in error "page already exists"
5) create link to page: "page doesn't exist"

**Comment by NGPixel** [comment] 2017-05-03 17:23
Duplicate of #88, already fixed in Beta 12.

**Closed by NGPixel** 2017-05-03 17:23 UTC
