### ISSUE TITLE
Commits with / in their name results in &#x2F;

### ISSUE THREAD

**Issue by Angristan** [Requarks/wiki#405] opened 2018-02-12 15:38 UTC
### Actual behavior

Commits with `/` in their name results in `&#x2F;`

Example: `Added linux&#x2F;web&#x2F;nginx.md`

![screenshot_12-02-2018_16-31-57](https://user-images.githubusercontent.com/11699655/36104560-a564f1a2-1012-11e8-88f2-dde348f92a2e.png)

### Expected behavior

Correct encoding.

Example: `Added linux/web/nginx.md`

### Steps to reproduce the behavior

Create a new file in a subfolder.

I'm using version v1.0.68.

Thanks for the cool software btw 🎉

**Comment by NGPixel** [comment] 2018-03-02 20:48
Duplicate of #185

**Closed by NGPixel** 2018-03-02 20:48 UTC
Labels: bug, deferred
