### ISSUE TITLE
GraphQL error with MySQL and FULL OUTER JOIN

### ISSUE THREAD

**Issue by glogrus** [Requarks/wiki#2071] opened 2020-06-16 19:37 UTC
**Describe the bug**
Page "/a/pages/visualize" has the following error:
```
[GraphQL error]: Message: select `pages`.`id` as `id`, `pages`.`path` as `path`, `title`, `pageLinks`.`path` as `link`, `pageLinks`.`localeCode` as `locale` from `pages` full outer join `pageLinks` on `pages`.`id` = `pageLinks`.`pageId` where `pages`.`localeCode` = 'en' - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'outer join `pageLinks` on `pages`.`id` = `pageLinks`.`pageId` where `pages`.`loc' at line 1, Location: [object Object], Path: pages,links
```

**To Reproduce**
1. Go to '/a/pages'
2. Click on 'Visualize'
3. See error

**Expected behavior**
Dendrogram representation of your pages.

**Host Info (please complete the following information):**
 - OS: CentOS 7
 - Wiki.js version: 2.4.107
 - Database engine: MySQL 8.0.20

**Additional context**
We don't have FULL JOINS on MySQL, but we can sure emulate them.

In file: server/graph/resolvers/pages.js replace code:
```
    /**
     * FETCH PAGE LINKS
     */
    async links (obj, args, context, info) {
      let results = []

      results = await WIKI.models.knex('pages')
        .column({ id: 'pages.id' }, { path: 'pages.path' }, 'title', { link: 'pageLinks.path' }, { locale: 'pageLinks.localeCode' })
        .fullOuterJoin('pageLinks', 'pages.id', 'pageLinks.pageId')
        .where({
          'pages.localeCode': args.locale
        })
```
with:
```
    /**
     * FETCH PAGE LINKS
     */
    async links (obj, args, context, info) {
      let results = []

      results = await WIKI.models.knex('pages')
        .column({ id: 'pages.id' }, { path: 'pages.path' }, 'title', { link: 'pageLinks.path' }, { locale: 'pageLinks.localeCode' })
        .leftOuterJoin('pageLinks', 'pages.id', 'pageLinks.pageId')
        .where({
          'pages.localeCode': args.locale
        }).unionAll(WIKI.models.knex('pages')
        .column({ id: 'pages.id' }, { path: 'pages.path' }, 'title', { link: 'pageLinks.path' }, { locale: 'pageLinks.localeCode' })
        .rightOuterJoin('pageLinks', 'pages.id', 'pageLinks.pageId')
        .where({
          'pages.localeCode': args.locale
        }))
```

**Comment by regevbr** [comment] 2020-06-24 14:40
duplicate of #1715
Will try to make a PR later today

**Comment by regevbr** [comment] 2020-06-24 14:42
Also doesn't work with sqlite

**Closed** 2020-06-24 22:51 UTC
