### ISSUE TITLE
Non existing pages with a path with only two letters that is not a language code create parsing errors on the 'Page not found' page.

### ISSUE THREAD

**Issue by misharigot** [Requarks/wiki#1567] opened 2020-03-06 10:56 UTC
**Describe the bug**
Non existing pages with a path with only two letters that is not a language code create parsing errors on the 'Page not found' page.

E.g.  'https://docs.requarks.io/ab'.

It does not happen when you go to 'https://docs.requarks.io/en'. I imagine because this is a valid language code.

**To Reproduce**
1. Go to 'https://docs.requarks.io/ab' or 'https://docs.requarks.io/cd' or 'https://docs.requarks.io/xy' etc. 
**This also happens when you deploy wiki.js yourself**.
1. See error

**Expected behavior**
Instead of `notfound.*` for docs.requarks.io or `newpage.*` in the case of the deployed wiki.js, it should show the correct content, e.g. `This page does not exist yet.`.

**Screenshots**

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04, Docker
 - Wiki.js version: 2.0.1
 - Database engine: postgres 9.7

**Comment by eeshugerman** [comment] 2020-03-30 06:30
Similar to (or duplicate of?) https://github.com/Requarks/wiki/issues/1292

**Closed** 2020-04-10 10:11 UTC
Labels: bug, contrib-easy

**Comment by misharigot** [comment] 2020-04-10 10:12
Yes, #1292 is the same issue, thanks 👍. I closed this one.
