### ISSUE TITLE
Redirect to original entry point after login

### ISSUE THREAD

**Issue by andreisusanu** [Requarks/wiki#501] opened 2018-04-23 07:37 UTC
### Actual behavior
I'm sharing a wiki page URL with my colleague. When the link is opened, my colleague gets redirected to the login page. After a successful login, the colleague is redirected to the main page, instead of the original page.

### Expected behavior
After login, redirect to the initial wiki page.

### Steps to reproduce the behavior
1. Go to any wiki page without being logged in. e.g. https://my.wiki/example
2. The login page is displayed. Login.
3. You will be redirected to https://my.wiki/ instead of the original entry point.

**Comment by NGPixel** [comment] 2018-04-29 16:16
Duplicate of #141

**Closed by NGPixel** 2018-04-29 16:16 UTC
