### ISSUE TITLE
Discord OAuth: Failed to obtain access token

### ISSUE THREAD

**Issue by RuscalWorld** [Requarks/wiki#2252] opened 2020-07-31 10:58 UTC
**Question**
I use Discord OAuth in my wiki. When user tries to sign in using Discord, it shows error "Failed to obtain access token". It worked well about a week ago, but now it doesn't work. I also have another instance of wiki.js on Ubuntu 20.04 with MariaDB and authorization works well there. I tried to make POST request as specified [here](https://discord.com/developers/docs/topics/oauth2#authorization-code-grant) (also tried discordapp.com) using CURL on my server to get access token and Discord gives me normal response. 

**Host Info (please complete the following information):**
OS: Docker
Wiki.js version: 2.4.107
Database engine: postgres 11.8

**Comment by Smankusors** [comment] 2020-07-31 12:28
Duplicate of #2164 

Btw how do you sent the CURL request?

**Comment by RuscalWorld** [comment] 2020-07-31 12:40
I've did something like this
```
curl --data "client_id=AAA&client_secret=BBB&grant_type=authorization_code&code=CCC&redirect_uri=https://example.com/login/discord/callback&scope=identify%20email%20guilds" https://discordapp.com/api/oauth2/token
```
where  
**AAA** - client ID from discord app settings  
**BBB** - client secret from discord app settings  
**CCC** - code from GET parameters on `https://example.com/login/discord/callback`

**Closed** 2021-03-21 00:54 UTC
Labels: help
