### ISSUE TITLE
[RC.17] Link Embeds not pointing to correct pages/URLs

### ISSUE THREAD

**Issue by S1M0N** [Requarks/wiki#1169] opened 2019-10-31 12:39 UTC
**Describe the bug**
When creating an embedded link to an internal page the URL is being generated with incorrect path info, resulting in a broken link that goes to a 404/create page. 

Format being used: `[Internal Link](internal-link)`  

**To Reproduce**
1. Go to your main home.
2. Create new page with data under root (i.e. `/test-page`)
3. Edit home page and add internal link to new page (i.e. `[Test Page](test-page)`
4. Save changes and then attempt to navigate to new internal page with created link. 
5. Get 404/create page 

**Expected behavior**
Using above format one would expect for this to point to `https://wiki.domain.tld/en/internal-link`, however it appears that `home` is being inserted into the link which results in an actual URL of `https://wiki.domain.tld/en/home/internal-link`, which is invalid. 

**Screenshots**
![image](https://user-images.githubusercontent.com/727018/67946244-49f6aa80-fbb7-11e9-9ca5-6e18fb721253.png)  
![test-page_working](https://user-images.githubusercontent.com/727018/67946265-5aa72080-fbb7-11e9-8644-c469229dea03.png)  
![test-page_home](https://user-images.githubusercontent.com/727018/67946259-5549d600-fbb7-11e9-8246-9982a97a5059.png)  
![image](https://user-images.githubusercontent.com/727018/67946311-78748580-fbb7-11e9-97c0-db38b8871a2d.png)  
![image](https://user-images.githubusercontent.com/727018/67946288-6b579680-fbb7-11e9-8abb-ae8328ff7617.png)  

**Host Info (please complete the following information):**  
 - OS: `Ubuntu 18.04 x64`  
 - Wiki.js version: `2.0.0-rc.17`  
 - Database engine: `PostgreSQL 10.10`
 - Node.js Version: `10.17.01`

**Additional context**
This issue did not exist on `2.0.0-beta.275` and appeared once I upgraded to `2.0.0-rc.17`.

I have discovered that prepending the internal pointer with `/` resolves this issue (i.e. `[Internal Link](/internal-link)` then points to correct page of `https://wiki.domain.tld/en/internal-link`), however this is counter to standard Markdown behavior. 
![test-page_working3](https://user-images.githubusercontent.com/727018/67946968-e53c4f80-fbb8-11e9-8210-3b3280dccd48.png)  
![test-page_working2](https://user-images.githubusercontent.com/727018/67946971-e8cfd680-fbb8-11e9-9faa-51f6601e1eaa.png)

**Comment by NGPixel** [comment] 2019-11-02 04:01
Duplicate of #1076

**Closed by NGPixel** 2019-11-02 04:01 UTC
