### ISSUE TITLE
[Regression] Markdown nested list broken

### ISSUE THREAD

**Issue by p-rintz** [Requarks/wiki#1114] opened 2019-10-21 03:27 UTC
**Describe the bug**
I updated from Beta 303 to the release candidate 1 and nested lists stopped working in markdown pages.

**To Reproduce**
1. Go to any  markdown page
2. Click on edit
3. Create a nested list in markdown

**Expected behavior**
I expected nested lists to still work.

**Screenshots**
Nested list code as it worked before:
![grafik](https://user-images.githubusercontent.com/13933258/67174619-01730c00-f3c3-11e9-8fd2-2d4a5bd8a49d.png)
Broken state:
![grafik](https://user-images.githubusercontent.com/13933258/67174640-1354af00-f3c3-11e9-8176-0e25ac1d7613.png)

**Host Info (please complete the following information):**
 - OS:  Archlinux; non-docker
 - Wiki.js version: RC1
 - Database engine: sqlite

**Comment by NGPixel** [comment] 2019-10-26 20:43
Fixed by e5774a89f1683623153546b8595318a7bb702ca4

**Comment by XerqJon** [comment] 2019-11-12 04:06
@NGPixel is the additional padding above a nested ul/ol element intentional or part of this bug as well?
![image](https://user-images.githubusercontent.com/3145572/68640989-665be680-04d7-11ea-809d-0d578f2018b4.png)
There's more vertical space between a parent / nested list elements than there is between elements at the same level.

I've not seen the same additional padding elsewhere (example below). If this is by design, I'll see about a css injection to tweak.
- Top level
    - Nested

**Comment by NGPixel** [comment] 2019-11-12 06:10
@XerqJon This is a bug.

**Comment by NGPixel** [comment] 2019-11-17 03:26
Fixed by 1c814638dac459e2182224e52d889aa8c8b36292

**Closed by NGPixel** 2019-11-17 03:26 UTC
Labels: RC, bug
