### ISSUE TITLE
Search Results return duplicates

### ISSUE THREAD

**Issue by klhilley** [Requarks/wiki#595] opened 2018-08-02 15:16 UTC
### Steps to Reproduce: Enter a keyword in the Search field, and view the Results list.
![searchissue](https://user-images.githubusercontent.com/39628227/43593315-74a9de2e-9645-11e8-9251-6974764ad4d8.png)

**Comment by NGPixel** [comment] 2018-08-02 23:38
Duplicate of #479 

Restart Wiki.js as a workaround. This will be fixed in 2.0.

**Closed by NGPixel** 2018-08-02 23:38 UTC
