### ISSUE TITLE
Unable starting dev branch

### ISSUE THREAD

**Issue by tuan-nng** [Requarks/wiki#634] opened 2018-09-17 18:03 UTC
### Actual behavior
I followed this guide to run the dev branch (https://docs.requarks.io/wiki/v/2.x/developers/getting-started#using-docker).
However, when I ran this command `make docker-dev-up`, I got this error

`  { sql:
     'alter table "pageHistory" add column "pageId" integer, add column "editorKey" varchar(255), add column "localeCode" varchar(2), add column "authorId" integer',
    bindings: [] },
  { sql:
     'alter table "pageHistory" add constraint "pagehistory_pageid_foreign" foreign key ("pageId") references "pages" ("id")',
    bindings: [] },
  { sql:
     'alter table "pageHistory" add constraint "pagehistory_editorkey_foreign" foreign key ("editorKey") references "editors" ("key")',
    bindings: [] },
  { sql:
     'alter table "pageHistory" add constraint "pagehistory_localecode_foreign" foreign key ("localeCode") references "locales" ("code")',
    bindings: [] },
  { sql:
     'alter table "pageHistory" add constraint "pagehistory_authorid_foreign" foreign key ("authorId") references "users" ("id")',
    bindings: [] },
  { sql:
     'alter table "pages" add column "editorKey" varchar(255), add column "localeCode" varchar(2), add column "authorId" integer, add column "creatorId" integer',
    bindings: [] },
  { sql:
     'alter table "pages" add constraint "pages_editorkey_foreign" foreign key ("editorKey") references "editors" ("key")',
    bindings: [] },
  { sql:
     'alter table "pages" add constraint "pages_localecode_foreign" foreign key ("localeCode") references "locales" ("code")',
    bindings: [] },
  { sql:
     'alter table "pages" add constraint "pages_authorid_foreign" foreign key ("authorId") references "users" ("id")',
    bindings: [] },
  { sql:
     'alter table "pages" add constraint "pages_creatorid_foreign" foreign key ("creatorId") references "users" ("id")',
    bindings: [] },
  { sql:
     'alter table "users" add column "providerKey" varchar(255) not null default \'local\', add column "localeCode" varchar(2) not null default \'en\', add column "defaultEditor" varchar(255) not null default \'markdown\'',
    bindings: [] },
  { sql:
     'alter table "users" add constraint "users_providerkey_foreign" foreign key ("providerKey") references "authentication" ("key")',
    bindings: [] },
  { sql:
     'alter table "users" add constraint "users_localecode_foreign" foreign key ("localeCode") references "locales" ("code")',
    bindings: [] },
  { sql:
     'alter table "users" add constraint "users_defaulteditor_foreign" foreign key ("defaultEditor") references "editors" ("key")',
    bindings: [] },
  { sql:
     'alter table "users" add constraint "users_providerkey_email_unique" unique ("providerKey", "email")',
    bindings: [] } ]
{ method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1, 2018-09-17T17:42:07.252Z, '2.0.0.js' ],
  __knexQueryUid: '9c48dbb4-0c1d-447d-96e1-cb9155fdc504',
  sql:
   'insert into "migrations" ("batch", "migration_time", "name") values (?, ?, ?)',
  returning: undefined }
{ method: 'update',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 0 ],
  __knexQueryUid: '0fae92b4-8663-4bcb-ab0f-cfeb4e7da724',
  sql: 'update "migrations_lock" set "is_locked" = ?',
  returning: undefined }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'e0ebb07e-2623-401c-963a-c6ca07d713ab',
  sql: 'select "settings".* from "settings"' }
2018-09-17T17:42:07.285Z [MASTER] warn: DB Configuration is empty or incomplete. Switching to Setup mode...
2018-09-17T17:42:07.288Z [MASTER] info: Purging old queue jobs: [ OK ]
2018-09-17T17:42:07.288Z [MASTER] info: Starting setup wizard...
2018-09-17T17:42:07.368Z [MASTER] error: ENOENT: no such file or directory, stat '/var/wiki/assets/favicon.ico'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Makefile:26: recipe for target 'docker-dev-up' failed
make: *** [docker-dev-up] Error 1
`

### Expected behavior
initialization should complete

### Steps to reproduce the behavior
Clone the project from GitHub (make sure to use the dev branch).

Start the development environment:

On Linux / macOS: make docker-dev-up

**Comment by baer95** [comment] 2018-09-17 18:21
As per my experience with the missing favicon error, the culprit is actually at a different place.

The file `client/components/admin/admin-system.vue` has a dependency called `mdi` which is imported in line 108-110 and used in 116-118. This npm-package does not exist anymore, which leads to `yarn install` failing.

Just comment out those six lines mentioned above since they are unused anyways execute `make docker-dev-up` again.

If this does not work, please provide us with the complete output of `make docker-dev-up`.

**Comment by tuan-nng** [comment] 2018-09-17 19:44
Great. It helped. Thanks :+1:

**Comment by NGPixel** [comment] 2018-09-18 01:12
Use the latest dev branch, the issue is now fixed.

@baer95 The six lines are actually used as vue components in the template section. Removing them would simply throw client side errors about missign components.

**Closed by NGPixel** 2018-09-18 01:12 UTC
