### ISSUE TITLE
Markdown URLs within local directory not rendered correctly 

### ISSUE THREAD

**Issue by systolan** [Requarks/wiki#1726] opened 2020-04-15 15:37 UTC
Within a markdown document, residing in a sub-folder, an URL to another document within the same sub-folder over "./" is not rendered correctly on the resulting pages.

**Steps to reproduce**
1. create a markdown document inside a sub-folder
1. create a link in the form of `[link](./other-document.md)`
1. observe the link is correct (!) in the preview
1. save and close the document
1. observe the actual link is now **incorrect** (!) and points to the same document we just edited.

**Host Info :**
 - OS: Ubuntu Server 18.04
 - Wiki.js version: 2.2.51 dockerized as described on the docs
 - Database engine: postgres 11.7

**Comment by Smankusors** [comment] 2020-04-15 20:33
This is similiar, or duplicate of #1547, #1201

**Closed** 2021-03-21 01:17 UTC
Labels: migrate
