### ISSUE TITLE
image file up error

### ISSUE THREAD

**Issue by userWek** [Requarks/wiki#2722] opened 2020-11-18 07:15 UTC
**Question**
error info->
with recursive `ancestors` as (select `id`, `name`, `slug`, `parentId` from `assetFolders` where `id` = 0 union select `a`.`id`, `a`.`name`, `a`.`slug`, `a`.`parentId` from `assetFolders` as `a` inner join `ancestors` on `ancestors`.`parentId` = `a`.`id`) select * from `ancestors` - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'recursive `ancestors` as (select `id`, `name`, `slug`, `parentId` from `assetFol' at line 1

**Host Info (please complete the following information):**
OS: [e.g. centos 7]
Wiki.js version: [Wiki.js  2.5.170]
Database engine: [mysql 5.7]

**Comment by Smankusors** [comment] 2020-11-18 08:17
Duplicate of #2149

**Closed** 2020-11-19 16:47 UTC
Labels: help
