### ISSUE TITLE
Can`t use more then 1 Google Auth

### ISSUE THREAD

**Issue by Vovcharaa** [Requarks/wiki#2941] opened 2021-01-22 16:23 UTC
**Bug in Google Authentication Strategy**
I cant use more then one Google Authentication Strategy
It essential to have this feature in my case because of using 2 different coop accounts with internal apps

**To Reproduce**
1. Add Google Authentication Strategy №1
2. Add Google Authentication Strategy №2
3. When logging in with Google Authentication Strategy №1 Wiki.js instead use Google Authentication Strategy №2

**Expected behavior**
I can logging in with both  Authentication Strategies without problems

**Host Info (please complete the following information):**
 - OS: Docker Container (Linux) (aws marketplace)
 - Wiki.js version: 5.170
 - Database engine: postgres 11.8

**Comment by applike-ss** [comment] 2021-02-09 14:52
I do see the same behaviour, same configuration as @Vovcharaa but instead of postgres 11.8 i am using 12.5.

We tried to set up wiki.js with multiple google authentication providers to be able to put people in different group depending on their business gmail domain.

**Comment by NGPixel** [comment] 2021-03-07 21:00
Duplicate of #2554

**Closed by NGPixel** 2021-03-07 21:00 UTC
