### ISSUE TITLE
User verification mail link results in error "this.ready.tap is not a function"

### ISSUE THREAD

**Issue by thorbenegberts** [Requarks/wiki#1668] opened 2020-04-03 19:22 UTC
(Wiki.js Version **2.2.51**)

### Actual behavior

User account verification page (link from email) opens with error `this.ready.tap is not a function`.

### Expected behavior

User account verification page (link from email) opens and verfies user account.

### Steps to reproduce the behavior

- User registers a new account with auth method "local" (email + password)
- User gets email "Verify your account"
- User clicks link "verify" with link https://wiki.hammertimekassel.de/verify/G-0HcUThsTgqTHBUQa8Oi
- Page opens with error `this.ready.tap is not a function`
    ![image](https://user-images.githubusercontent.com/3115618/78396753-3204d600-75f0-11ea-9a93-231130dfd278.png)
- The user is stuck in the situation. However, the user exists in the admin area as

**Comment by jonas920718** [comment] 2020-04-09 10:05
Same here. User is created, but Verify link in e-mail do not work

**Comment by Smankusors** [comment] 2020-04-09 19:48
can you give us your host info like issue template?

**Comment by joppehoekstra** [comment] 2020-04-10 09:02
Same issue here

**Comment by jonas920718** [comment] 2020-04-10 11:06
My host info:

OS: Ubuntu 18.04
Wiki.js version: 2.2.51
Database engine: postgres 12

**Comment by thorbenegberts** [comment] 2020-04-10 15:16
My host info:

- OS: Ubuntu 18.04 (created on DigitalOcean April 1, 2020)
- Wiki.js version: 2.2.51
- Database engine: Postgres 11.7
- Node.js: 12.16.1

**Comment by wanseob** [comment] 2020-04-18 12:43
I have the same problem, in my case I used an image with the AWS Marketplace one

**Comment by Latiosu** [comment] 2020-04-18 15:04
Reproduced the issue locally in development mode (on `master#53ceea74`) and also seeing some "Unable to acquire a connection" warnings in node logs. Perhaps unable to connect to KnexStore for some reason?

![image](https://user-images.githubusercontent.com/7020503/79641208-64f6be80-81d9-11ea-9741-3bc6403c67d9.png)

**Comment by Latiosu** [comment] 2020-04-19 00:25
Duplicate of #1613 
Raised an issue in brute-knex: https://github.com/llambda/brute-knex/issues/11

**Comment by wanseob** [comment] 2020-04-19 17:46
It looks good to use other OAuth2 like Google sign-in until this issue resolved. I was able to provide the wiki service to people with that option.

**Comment by NGPixel** [comment] 2020-04-22 03:22
Fixed by dae64f00a0587e854f4faa12f3450c47562abe0f

- removed dependency to brute-knex and refactored the lib to support knex 0.20+

**Closed by NGPixel** 2020-04-22 03:22 UTC
Labels: bug
