### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by AuspeXeu** [Requarks/wiki#2136] opened 2020-07-03 14:46 UTC
When creating a table with a content wider than the screen size of the machine you're viewing it on, it gets truncated instead of offering a way to scroll horizontally.

In the editor:
![image](https://user-images.githubusercontent.com/2115696/86479502-98fb6d80-bd4c-11ea-8806-3f849ec496d2.png)
Output:
![image](https://user-images.githubusercontent.com/2115696/86479537-a57fc600-bd4c-11ea-979e-649fbc94486b.png)

The output is only visible until column "Model" and the rest is truncated. No scrolling available.

**Comment by Smankusors** [comment] 2020-07-03 19:14
Duplicate of #2091

**Comment by NGPixel** [comment] 2020-07-03 21:24
Not the same thing @Smankusors , this is for tables. Unrelated to the scrolling the content tabs specifically.

**Comment by Smankusors** [comment] 2020-07-03 21:48
uh oh, sorry. I think I have seen this before. How about #1314? 😅

**Comment by NGPixel** [comment] 2020-07-03 22:05
Duplicate of #1314

**Closed by NGPixel** 2020-07-03 22:05 UTC
Labels: contrib-medium, ui

**Comment by AuspeXeu** [comment] 2020-09-04 08:26
#2340
