### ISSUE TITLE
Storage - GIT setup fails if the password has @

### ISSUE THREAD

**Issue by mercplus** [Requarks/wiki#2646] opened 2020-10-31 18:47 UTC
**Describe the bug**
If the Github password has @ in it, it would mess up the Git setup.

**To Reproduce**
1. Change Github password, make sure to have @ in the password string.
2. Setup a new github storage, with basic authentication.
3. Setup and further syncs would fail.

**Expected behavior**
Sync should initialize.

**Screenshots**

**Host Info (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04, Docker]
 - Wiki.js version: [e.g. 2.5.170]
 - Database engine: [e.g. postgres:11-alpine, docker]

**Comment by Smankusors** [comment] 2020-11-01 06:07
Duplicate of #840

**Closed** 2021-03-21 00:57 UTC
Labels: migrate
