### ISSUE TITLE
Page Contents Won't Scroll

### ISSUE THREAD

**Issue by TTriemstra** [Requarks/wiki#557] opened 2018-06-27 19:21 UTC
### Actual behavior
The Page Contents sidebar is static even when the contents exceed the vertical display size of the sidebar. Scrolling only occurs when a user reaches the very end of the document.

### Expected behavior
It would be nice if the sidebar could scroll to display all of the page contents, no matter where a user was in the document. This would make navigating long documents significantly easier.

### Steps to reproduce the behavior
To reproduce, view a document with ~20 headers (h1 or h2). The Page Contents sidebar will first scroll to cover the navigation menu, but will then stop scrolling until very close to the bottom of the document.

**Comment by NGPixel** [comment] 2018-06-30 00:00
Duplicate of #170

**Closed by NGPixel** 2018-06-30 00:00 UTC
