### ISSUE TITLE
Side Bar - all pages does not working on internet explorer 11

### ISSUE THREAD

**Issue by leandrocubas** [Requarks/wiki#316] opened 2017-11-13 18:39 UTC
### Actual behavior
When i select  all pages on internet explorer 11 the side bar doesn't appear like happens on Google Chrome.

### Expected behavior
the side bar show up when select all pages

### Steps to reproduce the behavior
just access all pages on internet explorer 11, it won't appear the side bar.

![image](https://user-images.githubusercontent.com/9282927/32742644-350bf2c0-c891-11e7-9893-dfc35b6f12b6.png)

**Comment by NGPixel** [comment] 2017-11-14 00:05
Duplicate of #266 

Will be fixed in 2.0.

**Closed by NGPixel** 2017-11-14 00:05 UTC
