### ISSUE TITLE
Can't edit pages on wiki.js

### ISSUE THREAD

**Issue by Axeolito** [Requarks/wiki#2753] opened 2020-11-24 14:40 UTC
**Question**
Hi! First, sorry for my english, i'm French so... ahah
I have a wiki.js on ubuntu since today and i got a huge problem. I can't edit pages. I'll try to explain. First i'm creating the page, everything goes ok but then when i want to go on that page and changes titles or put somes pictures in it i can't. I can't erase something i wrote before or if i press "enter" nothing happens. Is that a known bug ? Can someone help me? 

**Host Info (please complete the following information):**
OS: Ubuntu + docker
Wiki.js version: [e.g. 2.0.1]
Database engine: [e.g. postgres 9.7, mysql 5.7]

**Comment by Openanonwriter** [comment] 2020-11-24 23:45
Just started up a new server in a vm. I am having the same issue. 

Host Info:

**Comment by Axeolito** [comment] 2020-11-25 07:25
So, i'm not alone, i guess it's a good thing.. Ahah
Many of my friend got a wiki.js and don't have this issue so it's maybe fixable ?
I tried the same thing that you did, guess what? didn't succed neither..

**Comment by Weitspringer** [comment] 2020-11-25 19:51
I have the same problem!
With the use of the developer tools I found out that a js module named editor-ckeditor.js throws an error.
![ckeditor](https://user-images.githubusercontent.com/35311367/100275254-eed0ec00-2f5f-11eb-8e76-498384cd0309.PNG)
![ckeditor2](https://user-images.githubusercontent.com/35311367/100275259-f0021900-2f5f-11eb-83cb-2332e844fdee.PNG)

**Comment by Axeolito** [comment] 2020-11-26 07:32
Can't we update that ? Maybe it has been fixed in a new version ?

**Comment by Weitspringer** [comment] 2020-12-02 17:40
> 
> 
> Can't we update that ? Maybe it has been fixed in a new version ?

I use the most current version. In #2758 it was asked what browsers we used. I use Firefox, how about you?

**Comment by Axeolito** [comment] 2020-12-03 08:13
> 
> 
> > Can't we update that ? Maybe it has been fixed in a new version ?
> 
> I use the most current version. In #2758 it was asked what browsers we used. I use Firefox, how about you?

I use the most current version too and firefox too. Maybe we should try another browser ?

**Comment by mkalam-alami** [comment] 2020-12-07 21:56
Same problem here, after a few keypresses (or after the page finishes loading?), the editor doesn't react when using special keys like using Backspace or Enter. When opening the console, the CKEditor plugin errors at each keypress with various errors, usually one of:
* `Uncaught CKEditorError: can't access property "dep", a is undefined`
* `Uncaught CKEditorError: can't access property "observeArray", a is undefined`
* `Uncaught CKEditorError: Index or size is negative or greater than the allowed amount` 

My setup:

* WikiJS 2.5.170
* WYSIWYG editor
* Firefox

The good news is that so far I haven't been able to reproduce the bug on Chrome, so there's a workaround.

**Comment by NGPixel** [comment] 2020-12-09 03:28
Duplicate of #2758

**Closed by NGPixel** 2020-12-09 03:28 UTC
Labels: help
