### ISSUE TITLE
Other features not working on raspberry pi

### ISSUE THREAD

**Issue by mgonzaga1990** [Requarks/wiki#1504] opened 2020-02-20 08:08 UTC
I have installed the application using docker on my raspberry pi 3.
after creating pages. It seems that on the left side it only display Home only.. and other components says "comming soon"

**Comment by AuspeXeu** [comment] 2020-02-20 19:15
That's intended behaviour and not raspberry pi specific. You should close this issue.

**Comment by Smankusors** [comment] 2020-02-21 15:13
Unfortunately even though the main page have a lot of cool stuff, some are not still implemented yet (coming soon) :/

**Closed** 2020-02-22 02:48 UTC
Labels: help
