### ISSUE TITLE
Visual Editor. Tables

### ISSUE THREAD

**Issue by Scrik** [Requarks/wiki#2370] opened 2020-09-04 19:11 UTC
**Describe the bug**
large tables do not scale on the page and you have to zoom out in the browser to see all the information

**To Reproduce**
1. Create new page
2. Add table with 26 column and text
3. save
4. see table

**Expected behavior**
the table should scale to fit the screen

**Host Info (please complete the following information):**
OS: Centos 7
Wiki.js version: Stable 2.4.107
Database engine: postgres 11

**Comment by NGPixel** [comment] 2020-09-05 22:39
Duplicate of #1838

**Closed by NGPixel** 2020-09-05 22:39 UTC
