### ISSUE TITLE
Plant UML Crashed

### ISSUE THREAD

**Issue by mikkushukla** [Requarks/wiki#1887] opened 2020-05-14 13:05 UTC
**Describe the bug**
Plant UTL Not working in official documentation

https://docs.requarks.io/en/editors/markdown

![image](https://user-images.githubusercontent.com/12640686/81937756-a9774d80-9611-11ea-92e1-fe3c2b89a3b2.png)

**Comment by NGPixel** [comment] 2020-05-14 15:02
Duplicate of #1857

**Closed by NGPixel** 2020-05-14 15:02 UTC
