### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by brihanrohan** [Requarks/wiki#1132] opened 2019-10-23 12:59 UTC
Running v2.0.0 RC1
Docker-compose with wiki:beta and postgres:9-alpine

1. I ran the wiki v1 migration tool to get a fork of my old repo into v2 wiki for testing.
2. I forced the reindex of the pages using the "Import everything" tool in the git config page.
3. Breadcrumbs got auto generated.
4. I added a new locale: jp
5. I turned on multi-lingual namespacing
6. I edited a page and changed it's locale to jp

Problems:
A: [Bug] The breadcrumb didnt get updated and so now points to an en version of the page which doesnt exist.
B: [Difficulty] The breacrumbs that got generated reflect the structure of the original repo which was folder based. Each folder has been added as a breadcrumb. So now all of the first level breadcrumbs point to pages that dont exist.

Suggestion:
B: Either: 
[Feature request] This kind of breadcrumb should resolve to a new kind of page that lists all child pages.
[Feature request] Breadcrumbs for folders shouldnt be generated.

**Comment by NGPixel** [comment] 2019-10-27 21:42
(A) Fixed by c83eb255141e4cce12532081ea7b26821902f318
(B) This is by design. Breadcrumbs reflect the path. You'll be able to automatically have folder views on folders that don't have content yet in a future release.

**Closed by NGPixel** 2019-10-27 21:42 UTC
