### ISSUE TITLE
Font download failed

### ISSUE THREAD

**Issue by ghost** [Requarks/wiki#1708] opened 2020-04-12 17:00 UTC
**Describe the bug**
Fonts are not being downloaded during browsing as they should. The location does not exist. Wiki.js expects the fonts to be at http://{SERVER}/fonts/ but they really are located at http://{SERVER}/assets/fonts/

**To Reproduce**
1. Open a page with the markdown editor
2. Use the browser console to see the following error:

**Error message**
`GET http://{SERVER}/fonts/arabic/RobotoMono-Regular.woff2 net::ERR_ABORTED 404 (Not Found)`

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04, Docker
 - Wiki.js version: 2.2.51
 - Database engine: SQLite

**Additional context**
Seen on Firefox 74.0.1 and Brave 1.5.123 on macOS 10.15.4

**Comment by Smankusors** [comment] 2020-04-12 17:46
the steps to reproduce this is still missing something, because I cannot reproduce this in fresh install.

**Comment by key4key** [comment] 2020-04-12 19:11
My apologies, I meant to say "Edit a page in markdown editor" as the first step. I'm assuming that you should also be able to look at the code for where the fonts are called and see the discrepancy in location between /fonts/ and /assets/fonts/.

**Comment by Smankusors** [comment] 2020-04-12 19:49
well no, I know what do you mean by "Open a page with the markdown editor", but in my browser it never try to download "/fonts/arabic/RobotoMono-Regular.woff2". So there's still something missing on steps to reproduce.

**Comment by NGPixel** [comment] 2020-06-02 02:15
Fixed by 4c038c4ad67b7527e7f8ebb067917718f8d6f0d7

**Closed by NGPixel** 2020-06-02 02:15 UTC
